### ISSUE TITLE
browse-url doesn't work as an embark-act action from the minibuffer

### ISSUE THREAD

**Issue by jakanakaevangeli** [oantolin/embark#182] opened 2021-03-09 16:52 UTC
To reproduce with emacs -q:

Press M-s M-w, type some random url and then use `embark-act` to open it with
`browse-url` (with `C-. M-x browse-url RET` for example).

This happens to all commands that use `browse-url-interactive-arg` in their
interactive spec because `(this-command-keys)` has zero elements.

**Comment by oantolin** [comment] 2021-03-09 16:57
I can't reproduce this. Using `M-x browse-url` does open the URL for me when used as an action from the minibuffer (I tried from `M-s M-w` and from `find-file`).

**Comment by oantolin** [comment] 2021-03-09 17:04
Oh, it does give an error if I try exactly the same thing from `emacs -Q`.

**Comment by oantolin** [comment] 2021-03-09 17:07
I bet this is one of those things that moving to `set-transient-map` would fix.

**Comment by jakanakaevangeli** [comment] 2021-03-09 17:47
Perhaps set--this-command-keys could be abused, so before
command-execute, we could do something like

    ;; Pacify commands that access (this-command-keys)
    (when (= 0 (length (this-command-keys)))
      (set--this-command-keys (kbd "RET")))

**Comment by oantolin** [comment] 2022-02-14 19:31
Sorry I took so long to fix this, @jakanakaevangeli. Thanks a lot for pointing out a solution. The only thing I did a little differently is try to use the key binding used to invoke the action if possible.

**Closed by oantolin** 2022-02-14 19:31 UTC
