### ISSUE TITLE
Error Exit the Dired exported buffer if a file/folder is renamed

### ISSUE THREAD

**Issue by aadi58002** [oantolin/embark#650] opened 2023-07-13 17:11 UTC
Hello there,
![image](https://github.com/oantolin/embark/assets/96418027/7f610221-e5c1-4ba3-bd60-9520cc9e9dca)

I exported one of my folder which partial matching with dired ex:- `./s/l` lists files from my three folders. Here as example
It list all the letter files

![image](https://github.com/oantolin/embark/assets/96418027/141ca478-ba60-45ca-a2cf-16a1f4c64cc7)

But if i rename any of them and write it . The rename takes place but 
```elisp
Debugger entered--Lisp error: (file-missing "Reading directory" "No such file or directory" "star1/letter1")
  #<subr insert-directory>("star1/letter1" "--dired -AGFhlv --group-directories-first --time-s..." nil nil)
  ls-lisp--insert-directory(#<subr insert-directory> "star1/letter1" "--dired -AGFhlv --group-directories-first --time-s..." nil nil)
  apply(ls-lisp--insert-directory #<subr insert-directory> ("star1/letter1" "--dired -AGFhlv --group-directories-first --time-s..." nil nil))
  insert-directory("star1/letter1" "--dired -AGFhlv --group-directories-first --time-s..." nil nil)
  dired-insert-directory("/home/aditya-yadav/Personal/Demo/" "-AGFhlv --group-directories-first --time-style=lon..." ("star1/letter1" "star2/letter2" "star3/letter3") nil t)
  dired-readin-insert()
  #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_47>()
  combine-change-calls-1(1 227 #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_47>)
...
```

The exported buffer closes

**Comment by oantolin** [comment] 2023-07-13 17:49
I couldn't reproduce this. I created a directory structure like the one you show, exported and then renamed one file by two methods: using dired's `R', and using `embark-act r`. In both cases the file was renamed and I got no error message. Could you tell me in more detail how you renamed your file?

Also, this might have to do with some extra configuration you have for dired. Can you reproduce the problem starting from `emacs -Q`?

**Comment by aadi58002** [comment] 2023-07-13 18:30
Sorry i forgot to tell you that i renamed the file by editing it in the exported buffer. By entering insert mode in a dired buffer.

**Comment by oantolin** [comment] 2023-07-13 19:08
Oh, thanks, I can reproduce it now! But I think this is a bug in dired, actually. Here's a way to reproduce it that does involve Embark at all:

1. Evaluate the expression `(dired '("." "star1/letter1" "star2/letter2" "star3/letter3"))` to create a dired buffer listing those files.

2. Now rename one of the files using dired editable mode.

You should see the same error. I'm closing because I think this should be fixed directly in dired.

**Closed by oantolin** 2023-07-13 19:08 UTC
