### ISSUE TITLE
Org link as property value not recognized as link

### ISSUE THREAD

**Issue by gusbrs** [oantolin/embark#666] opened 2023-09-22 12:46 UTC
Hi @oantolin !

When an Org property has a link as value, the link is not recognized as such by Embark.  Consider, for example:

```org
* Heading
:PROPERTIES:
:LINK: [[https://github.com/oantolin/embark][oantolin/embark: Emacs Mini-Buffer Actions Rooted in Keymaps]]
:END:
```
With point on the link call `embark-act` (then `embark-cycle`). The recognized targets are, in sequence: identifier, expression, sentence, paragraph, and defun. No org-url-link.

(On Embark 0.23, Emacs 29.1).

**Comment by oantolin** [comment] 2023-09-22 13:05
Yeah, Org says the smallest org-element containing point is the entire property line with key "LINK" and value the string " [[https://github.com/oantolin/embark][oantolin/embark: Emacs Mini-Buffer Actions Rooted in Keymaps]]". In other words, it seems like in Org property values are just plain strings, they're not expected to be structured.

I guess in cases like this it might be advisable to against Org's grammar and insist that that is a link, but I worry about complicating `embark-org` for a corner case which probably is not that common.

**Comment by gusbrs** [comment] 2023-09-22 13:16
What Org syntax (https://orgmode.org/worg/org-syntax.html#Node_Properties) says about it is: 

> VALUE (optional)
>     A string containing any characters but a newline.

I'm not sure how hard the interpretation of string was meant to be there, but it seems that, in practice, the code is taking it quite literally. Anyway, I agree with your caution there, this is no business of Embark. I wasn't aware Embark was using `org-element`, I just "found the issue" and reported. Sorry for the noise.

**Comment by minad** [comment] 2023-09-22 14:05
What's odd here is that the link is highlighted and activated by Org. I think this is a bug in the org-element API and should be fixed there.

**Comment by oantolin** [comment] 2023-09-22 14:17
Yeah, it's worth reporting to Org. Will you do that @gusbrs? I'll close this issue because the fix should be made in Org instead.

**Closed by oantolin** 2023-09-22 14:17 UTC

**Comment by gusbrs** [comment] 2023-09-22 15:02
> Will you do that @gusbrs?

OK, I can do it later on. I'm not sure what the "fix" will be, though. As noted, "correct behavior" will depend on interpretation.

**Comment by minad** [comment] 2023-09-22 15:16
The problem is that Org seems to be inconsistent. The markup is highlighted but not recognized by the org-element API. So I think the first step is to clarify the desired behavior.

**Comment by minad** [comment] 2023-09-22 15:29
> "Links in properties" are useful and, depending on how this goes, they may be gone...

Yes, this could happen. So chose your arguments wisely. :)

**Comment by gusbrs** [comment] 2023-09-22 15:33
> Yes, this could happen. So chose your arguments wisely. :)

I only see the inconsistency itself to report. But, perhaps you are wiser than me. ;-) Would you prefer to do it?

**Comment by minad** [comment] 2023-09-22 15:36
No, I won't report this and I would also be the wrong person to make the case since I don't care much about links in properties. ;)

The bug seems to be subtle. The link is correctly recognized in these snippets:

~~~
* Heading
:something:
:LINK: [[https://github.com/oantolin/embark][oantolin/embark: Emacs Mini-Buffer Actions Rooted in Keymaps]]
:END:

* Heading

:PROPERTIES:
:LINK: [[https://github.com/oantolin/embark][oantolin/embark: Emacs Mini-Buffer Actions Rooted in Keymaps]]
:END:
~~~

But not in this snippet:

~~~
* Heading
:PROPERTIES:
:LINK: [[https://github.com/oantolin/embark][oantolin/embark: Emacs Mini-Buffer Actions Rooted in Keymaps]]
:END:
~~~

It seems that the property drawer has some special logic, but other drawers support links.

**Comment by gusbrs** [comment] 2023-09-22 15:40
> The link is correctly recognized in these snippets:
> 
> ```
> * Heading
> :something:
> :LINK: [[https://github.com/oantolin/embark][oantolin/embark: Emacs Mini-Buffer Actions Rooted in Keymaps]]
> :END:
> 
> * Heading
> 
> :PROPERTIES:
> :LINK: [[https://github.com/oantolin/embark][oantolin/embark: Emacs Mini-Buffer Actions Rooted in Keymaps]]
> :END:
> ```

These are regular drawers (for the second case, "the properties drawer" must immediately follow the heading).


> But not in this snippet:
> 
> ```
> * Heading
> :PROPERTIES:
> :LINK: [[https://github.com/oantolin/embark][oantolin/embark: Emacs Mini-Buffer Actions Rooted in Keymaps]]
> :END:
> ```

This is "the actual properties drawer".

**Comment by minad** [comment] 2023-09-22 15:45
@gusbrs Yes, so it is probably a bug and you are not supposed to use links in property drawers. :shrug:

@oantolin On a related note, it would be great if Embark supported Org links in arbitrary buffers which can be accessed via `org-open-at-point-global`, such that we get hyperbolic intergalactical cross linking. The problem is that the target finder for this should not load Org early on. We would need our own regexp target finder and if that matches call `org-element-context`, or even use the match data directly, which would render this issue irrelevant.

**Comment by oantolin** [comment] 2023-09-22 17:02
> On a related note, it would be great if Embark supported Org links in arbitrary buffers which can be accessed via `org-open-at-point-global`, such that we get hyperbolic intergalactical cross linking.

I've thought about that. I think if I personally used org links in non-org files I would have added this to Embark by now. Maybe adding this to Embark would get me to start using links like that. :)

One simple choice would be to not detect them until Org is loaded, i.e., to put the target finder in embark-org.

**Comment by minad** [comment] 2023-09-22 17:12
> I think if I personally used org links in non-org files I would have added this to Embark by now.

I don't use the functionality much, but it can be nice for example to link to issues from source. The syntax is lightweight. See for example:

https://github.com/minad/consult/blob/43380042daaaf57f60aa22962a97ed904a7d56ce/consult.el#L1524

~~~ elisp
  (org-link-set-parameters
   "gh"
   :follow
   (lambda (issue _arg)
     (when (string-match "\\`\\([^#]+\\)#\\([[:digit:]]+\\)\\'" issue)
       (browse-url (format "https://github.com/%s/issues/%s"
                           (match-string 1 issue) (match-string 2 issue))))))
~~~

But this example also shows that the idea of using a regexp to determine the link won't work. To detect the link we already need the knowledge of the available link types.

> One simple choice would be to not detect them until Org is loaded, i.e., to put the target finder in embark-org.

Yes. It would be better if the  links are accessible right away, as they are with autoloaded `org-open-at-point-global`, but that won't work because of the lack of information.

Therefore you are right that Org must be already loaded. But running `org-element-context` on the example above doesn't seem to work. It seems that `org-open-at-point-global` does something special.

**Comment by gusbrs** [comment] 2023-09-22 18:43
For reference, reported at: https://lists.gnu.org/archive/html/emacs-orgmode/2023-09/msg00402.html

**Comment by oantolin** [comment] 2023-09-22 18:59
> It seems that `org-open-at-point-global` does something special.

It does regexp matching, basically `(org-in-regexp org-line-re)`. The reason I wanted to have org already loaded for the target finder is so I don't have to maintain a copy of the unwieldy regexp `org-link-any-re`.

**Comment by oantolin** [comment] 2023-09-22 19:00
> This example also shows that the idea of using a regexp to determine the link won't work. To detect the link we already need the knowledge of the available link types.

You're right, of course, for a fixed regexp. The beauty of `org-link-any-re` is that org updates it when you define a new link type.

**Comment by minad** [comment] 2023-09-22 19:05
@oantolin The regexp is not only unwieldy, it contains crucial information depending on the available link types:

- `no:link` 👎
- `gh:oantolin/embark#666` 🤘

**Comment by minad** [comment] 2023-09-22 19:11
So shall we add a special link finder which uses `org-link-any-re` instead of the `org-element-context`, which is only available if embark-org.el is loaded? This would solve the hyperbolic interlinking (when Org is loaded) and elegantly circumnavigate #666 at the same time. 🤘

**Comment by gusbrs** [comment] 2023-09-23 10:29
Ihor's reply to the report was the following:

> > When a link is placed as a property value, `org-element-context' does
> > not recognize it as a link.
>
> It is expected and intentional: https://list.orgmode.org/orgmode/877d8llha9.fsf@nicolasgoaziou.fr/.
>
> > In particular, the "link" element is not present, as would be the case
> > if the exact same link were not inside the property drawer. On the
> > other hand, the link is active (fontified, works, etc.). Thus,
> > `org-element.el` and `ol.el` seem to disagree as to what that part of
> > the buffer actually is.
>
> This is intentional. org-agenda and fontification deliberately recognize
> links in more contexts compared to org-element and export. Same for
> timestamps. For example, see `org-at-timestamp-p'.
>
> For ol.el, the links are open inside property drawer for convenience.
> Below is a code responsible for this case from `org-open-at-point':
>
>        ;; No valid link at point.  For convenience, look if something
>        ;; looks like a link under point in some specific places.
>        ((memq type '(comment comment-block node-property keyword))
>         (call-interactively #'org-open-at-point-global))

So it is indeed deliberate not only that the link is not recognized by `org-element` but also that the link works regardless. And Org itself uses `org-open-at-point-global` for that. (Well, at least I escaped from a "fix". No "wisdom" would have saved me.  :-)

**Comment by minad** [comment] 2023-09-23 20:34
@gusbrs I think Embark should then use the regexp to recognize links everywhere as I had mentioned in 
https://github.com/oantolin/embark/issues/666#issuecomment-1731920545.

**Comment by gusbrs** [comment] 2023-09-23 20:42
@minad Sounds like a good plan. I'd certainly be happy with it.  :-)

**Comment by oantolin** [comment] 2023-09-23 20:51
Do either of you know whether `org-open-at-point-global` can fully substitute for `org-open-at-point`?

**Comment by minad** [comment] 2023-09-23 20:57
No, it doesn't, by inspection of the code. In Org buffers you better use `org-open-at-point`. I think I had pasted this before somewhere - I use the following command for dwim at point. It uses `org-open-at-point` in Org buffers, `org-open-at-point-global` elsewhere and of course falls back to `embark-dwim`.

~~~ elisp
(defun +embark-dwim ()
  "Act at point with Embark or Org."
  (interactive)
  (or
   (and (derived-mode-p 'Info-mode)
        (Info-try-follow-nearest-node))
   (and (derived-mode-p 'markdown-mode)
        (ignore-errors (or (markdown-follow-thing-at-point t) t)))
   (if (derived-mode-p 'org-mode)
       (or (ignore-errors (or (org-ctrl-c-ctrl-c) t))
           (ignore-errors (or (org-open-at-point) t)))
     (ignore-errors (or (org-open-at-point-global) t)))
   (when-let (button (get-char-property (point) 'button))
     (if (widgetp button)
         (call-interactively 'widget-button-press)
       (push-button))
     t)
   (when-let ((maps (delq nil (list (get-char-property (point) 'keymap)
                                    (get-char-property (point) 'local-map))))
              (map (make-composed-keymap maps))
              (cmd (or (lookup-key map "\r") (lookup-key map [mouse-1])))
              ((functionp cmd)))
     (funcall cmd)
     t)
   (embark-dwim)))
~~~

**Comment by oantolin** [comment] 2023-09-23 21:16
It feels like there's a story behind that `(function cmd)` in the local keymaps code, @minad. :)

**Comment by minad** [comment] 2023-09-23 21:21
No idea, maybe I didn't add support for keyboard macros? I don't recall the reasons for all the conditions. Looking at it now it seems that Emacs is horrendously incoherent when all I want is to click a simple link.

**Comment by oantolin** [comment] 2023-09-24 06:49
So I'm trying to determine whether I need to write a custom default action for org links or not. (The custom action would just call `org-open-at-point` in org buffers, `org-agenda-open-link` in org agenda buffer and `org-open-at-point-global` in other buffers.) But I decided to test `org-open-at-point` and `org-open-at-point-global` first to see if either one of those would work in all cases.

As @minad said above, those two commands are not equivalent: they both handle a variety of things besides links (which is probably why they don't have "link" in the name), and not exactly the same set of things, but when it comes to actual org links they do seem to try to do the same thing. The difference is that `org-open-at-point` runs the `org-element` parser in the buffer where the link is are and `org-open-at-point-global` instead inserts just the link (as matched by the `org-link-any-re`) into a temporary buffer and then parses that (with a special link-only parser, `org-element-link-parser`).

As you might expect, this means that `org-open-at-point` can get confused in non-org buffers because it tries to parse as org syntax a chunk of the buffer that may be bigger than just the link (although it does actually seem to work in most cases even in non-org buffers!). On the other hand I think that `org-open-at-point-global` can handle all org links in any type of buffer. At least, it worked on a variety of link types and formats I tried in both org and non-org buffers. I tried bare links, links in angle brackets, links in double square brackets with and without descriptions and I tried them both in an org buffer and in a Lisp buffer.

I think I'll just use `org-open-at-point-global` as the default action for links and if we see any trouble then I'll write a function that delegates to the right one instead as described above. But my current belief is that for actual links `org-open-at-point-global` just works everywhere ---and the reason it can't replace `org-open-at-point` is because of the other types of things it can open, like footnotes and citations and source blocks (opening a source block seems to mean jumping to the results); all of which are irrelevant for embark-org link actions.

**Comment by oantolin** [comment] 2023-09-24 07:01
OK, done, 7758a1ac64d784fa71f14b202b7a26c27f29d03e.

**Comment by minad** [comment] 2023-09-24 08:50
Thanks! Should `org-link` still be part of `embark-org--types`? I suggest to expand the docstring of the regexp org link target finder slightly, mentioning that it runs in arbitrary buffers/contexts and that for this reason it doesn't rely on the org-element API. Just as a reminder when looking at it again in a year. :)

**Comment by oantolin** [comment] 2023-09-24 09:19
I decided to leave org-link in embark-org--types for now. If the two target finders find exactly the same link then Embark's target deduplication takes care of showing only one. But if the regexp approach ever gives a differs result from the parser-based one, then we'll see two consecutive slightly different link targets. So I left them both in as an experiment to see if that happens.

**Comment by minad** [comment] 2023-09-24 09:28
On 9/24/23 11:19, Omar Antolín Camarena wrote:
> I decided to leave org-link in embark-org--types for now. If the two
> target finders find exactly the same link then Embark's target
> deduplication takes care of showing only one. But if the regexp approach
> ever gives a differs result from the parser-based one, then we'll see
> two consecutive slightly different link targets. So I left them both in
> as an experiment to see if that happens.

Okay, sounds good!

**Comment by gusbrs** [comment] 2023-09-24 10:56
@oantolin Thank you!
