### ISSUE TITLE
choose-completion (RET) in a completion buffer does not work with embark-act

### ISSUE THREAD

**Issue by rswgnu** [oantolin/embark#193] opened 2021-03-26 07:26 UTC
When the embark-act prompt is live and I have pressed C-h to show possible completions, if I switch to the completion buffer and press RET, instead of inserting the appropriate completion, it cancels the embark-act prompt.  Please fix this so we can select potential completions with the mouse.

**Comment by oantolin** [comment] 2021-03-26 13:20
Oh, thanks for reporting this! It seems I never tried that combination. I'll look into it.

**Comment by oantolin** [comment] 2021-03-26 14:06
I can't reproduce this bug. I tried both in my personal configuration and in `emacs -Q`. And in both cases, if I run embark-act, press `C-h` and then `M-v` to switch to the `*Completions*` buffer I am able to select an action with `RET` or with the mouse and the action runs.

**Comment by oantolin** [comment] 2021-03-26 15:34
I think I'm going to need some help in reproducing this bug before I can fix it. In particular I just noticed you didn't say what you are using to display the completions after pressing `C-h` and I just assumed it was the `*Completions*` buffer as produced by `switch-to-completions` or `minibuffer-completion-help`, but maybe you are using something else? A recipe starting from `emacs -Q` would be greatly appreciated.

**Comment by rswgnu** [comment] 2021-03-26 15:49
Thanks, Omar.  You are correct and I was able to reproduce the behavior you
see this morning.  The issue is one between Hyperbole and the completion
system that I will resolve, not embark.  Hyperbole wants to insert the
selected completion without exiting the minibuffer (until a second,
confirming selection is made) but choose-completion is called and this is
forcing a minibuffer exit on the first completion selection.

**Comment by oantolin** [comment] 2021-03-26 16:07
It sounds like I can close this issue, then. Though we can keep writing here if there is anything more to discuss, of course, and we can reopen the issue if appropriate, too.

**Closed by oantolin** 2021-03-26 16:07 UTC

**Comment by rswgnu** [comment] 2021-03-26 17:22
Yes, please close.

-- Bob
