### ISSUE TITLE
Launching consult-*grep from find-file dialogs etc.

### ISSUE THREAD

**Issue by andersjohansson** [oantolin/embark#252] opened 2021-07-01 13:14 UTC
In helm when doing `find-file` you can use `C-s` to launch a grep (or ripgrep etc) search in the currently selected directory. I often used this to navigate to the right directory for launching a search.

I thought something like this should work also for embark and consult, but when launching consult-ripgrep directly from a find-file selection, the path is added as the search string, instead of using the path as the starting point of the search.

Defining and binding this helper function in `embark-file-map` gave me the behaviour I wanted. I am wondering if something like this should be added to `embark-consult`, or if I am missing something.

```emacs-lisp
(define-key embark-file-map "s" #'aj/consult-ripgrep-from-dir)
(defun aj/consult-ripgrep-from-dir (file)
  (consult-ripgrep (file-name-directory file)))
```

**Comment by oantolin** [comment] 2021-07-30 13:41
Sorry about leaving this here unanswered for so long.

Doesn't consult-ripgrep prompt for the directory with `C-u`? This means you can use `C-u C r` as the action (`C r` is bound to `consult-ripgrep` by the `embark-consult` package, if you aren't using it, instead of `C r` just use your normal keybinding for `consult-ripgrep`).

Your solution is still better for two reasons:

- `C-u C r` will take the entire candidate as the directory, including the file portion if it has one; in other words, it wouldn't apply `file-name-directory` for you as your solution does.
- `C-u C r` will require you to press `RET` to confirm the directory (again, assuming you use the `embark-consult` package); this is because Embark's idea of when to automatically press `RET` for you has the granularity of individual functions, so the `embark-consult` package sets up `consult-ripgrep` to not press `RET` for you so you can scroll through the search results or further filter them, but there is no way to say "ah, but if `consult-ripgrep` was called with `C-u`, then _do_ press `RET` at the directory prompt".

We can definitely discuss adding this action to embark-consult, but as you see using `C-u C r` is fairly close already, and the action is very small and easy to define so people can just put it in their `init.el` like you did. (One tiny advantage of having people write their own is less cluttered action keymaps: in `embark-consult` I'd probably have to put similar actions for all of consult's async search commands, but if you only ever use ripgrep, your config can have only `aj/consult-ripgrep-from-dir`.)

**Comment by minad** [comment] 2022-04-22 14:03
Has this issue been resolved by the recent addition of `embark--cd`?

**Comment by oantolin** [comment] 2022-04-23 01:27
Not quite, the issue is that the current behavior of `consult-grep` when used as an action is "start a search for the target". In this issue, the desired behavior is "do *not* search for the text of the target, but do start a search in th directory associated to the target".

If we don't mind losing the ability to quickly search for a file name, we could just combine the two behaviors into "*if* the target is a file, buffer, bookmark or library, then do not search for the target but do start the search in its directory; for any other type search for the text of the target".

**Comment by oantolin** [comment] 2022-04-23 01:28
I actually that's pretty sensible dwim behavior, I think I'll make that change in embark-consult.

**Closed** 2022-04-23 01:57 UTC
