### ISSUE TITLE
Nicer embark which-key menus

### ISSUE THREAD

**Issue by minad** [oantolin/embark#50] opened 2020-12-15 19:46 UTC
I found a way to enhance the consult narrowing menu such that which-key shows a description instead of the command name. E.g. for the buffer narrowing it shows "< Widen b Buffer f File ..."  generated by which-key.

See here https://github.com/minad/consult/blob/eaebab54450d859bbc5eb8c83c2fd7585ad2e2e6/consult.el#L395.

Something like this could be an option for embark too!

**Comment by minad** [comment] 2020-12-16 19:35
![wk](https://user-images.githubusercontent.com/50754/102397469-34705a00-3fde-11eb-9e24-bdc53a1ed9d6.png)

**Comment by oantolin** [comment] 2020-12-25 20:03
I don't like this. Why did which-key invent its own way of assigning descriptions to keys? What's wrong with the standard method? Here's how you usually assign descriptions to keymaps and to individual keys bound in them:

```elisp
(defvar file-ops-map
  (let ((map (make-sparse-keymap "File operations")))
    (define-key map "c" '("Copy" . copy-file))
    (define-key map "d" '("Delete" . delete-file))
    (define-key map "r" '("Rename" . rename-file))
    map))

(global-set-key (kbd "C-c f") file-ops-map)
```

**Comment by minad** [comment] 2020-12-25 20:12
It is not as bad as you think - this is an implementation detail. They are using their own which-key pseudo keys in order to have a fast lookup of replacements. 

I would probably preferred if they used separate hash tables for the replacements or just support menu-items. The assignment of descriptions to keys translates to menu items internally. Unfortunately they are not supported correctly by which-key. See https://github.com/justbur/emacs-which-key/issues/177  for the issue. They are not supporting it since which-key parses describe-bindings, and *upstream itself* does not support menu items correctly.

I am using the which-key pseudo-keys for the Consult narrowing menu for now since it just works, but I guess this will be revisited at some point when which-key/upstream adds support for menu-items. But I am not feeling strongly enough to contribute support for it myself. 

See also my comment here https://github.com/minad/consult/blob/eaebab54450d859bbc5eb8c83c2fd7585ad2e2e6/consult.el#L395.

**Comment by oantolin** [comment] 2020-12-25 20:20
> The assignment of descriptions to keys translates to menu items internally.

I'm sorry, I don't know anything about menu items. Are you saying that those `define-key` calls I put in the example above turn into some sort of menu item? Or were you talking about which-key?

In the example I gave, this is the keymap that gets built:

```elisp
(keymap
 (114 "Rename" . rename-file)
 (100 "Delete" . delete-file)
 (99 "Copy" . copy-file)
 "File operations")
```

Are you saying those entries are called menu items? I thought menu items were something else.

**Comment by minad** [comment] 2020-12-25 20:28
>  Are you saying that those define-key calls I put in the example above turn into some sort of menu item?

Right, they are not menu-items (I wrongly categorized them as such since menu-items also have a description, but they are not same). Still, the description is still not printed by describe-bindings and therefore not shown by which-key unfortunately. So neither menu-items nor these (string . def) pairs are supported :(

**Comment by minad** [comment] 2020-12-25 20:30
Where are these keybinding definitions shown btw? We are not showing them in marginalia, and if I am defining keys I never specify a description and I only have seen this rarely. This is probably also the reason for the missing support by describe-bindings.

**Comment by oantolin** [comment] 2020-12-25 20:32
They appear in the echo area! With the example above, try pressing `C-c f`. You should see: `File operations: Rename, Delete, Copy`.

**Comment by oantolin** [comment] 2020-12-25 20:35
Also try modifying the example to bind `rename-file` to `m`, say. Then the string in the echo area will show `m = Delete`, instead of just `Delete`. Emacs checks (case insensitively) if the description starts with the letter in the keybinding!

**Comment by oantolin** [comment] 2020-12-25 20:35
It's like a mini which-key that's built-in.

**Comment by minad** [comment] 2020-12-25 20:46
Interesting, I have never seen that. Is this used for anything built-in? Not a bad thing but kind of limited.

**Comment by oantolin** [comment] 2020-12-25 20:58
The only built-in keymap I know of that uses this is `facemenu-keymap` in `facemenu.el`

**Comment by minad** [comment] 2020-12-25 21:12
Uh, facemenu. Who uses this? It does not even work with font-lock.

**Comment by oantolin** [comment] 2020-12-25 21:13
I certainly don't use it. 🤷

**Comment by oantolin** [comment] 2020-12-30 00:17
For some reason I cannot get this to work. From your code in consult and from the which-key source I though this should work:

```elisp
(defmacro embark-define-keymap (name doc &rest bindings)
  "Define keymap variable NAME.
DOC is the documentation string.
BINDINGS is the list of bindings."
  (declare (indent 1))
  (let* ((map (make-symbol "map"))
         (parent (if (eq :parent (car bindings)) (cadr bindings)))
         (bindings (if parent (cddr bindings) bindings)))
    `(defvar ,name
       (let ((,map (make-sparse-keymap)))
         ,@(mapcan (pcase-lambda (`(,key ,fn ,desc))
                     (when (stringp key) (setq key (kbd key)))
                     `((define-key ,map ,key ,(if (symbolp fn) `#',fn fn))
                       ,@(when desc
                           (let ((idx (- (length key) 1)))
                             `((define-key ,map
                                 ,(vconcat (seq-take key idx)
                                           (vector 'which-key (elt key idx)))
                                 '(which-key (,desc))))))))
                   bindings)
         ,(if parent `(make-composed-keymap ,map ,parent) map))
       ,doc)))
```

Which you use as follows:

```elisp
(embark-define-keymap embark-file-map
  "Keymap for Embark file actions."
  ("f" find-file "Open")
  ("o" find-file-other-window "Other window")
  ("d" delete-file "Delete")
  ("D" delete-directory "Delete directory")
  ("r" rename-file "Rename")
  ("c" copy-file "Copy")
  ("!" shell-command "Shell command")
  ("&" async-shell-command "Async command")
  ("=" ediff-files "Ediff")
  ("e" embark-eshell "Eshell")
  ("+" make-directory "Make directory")
  ("I" embark-insert-relative-path "Insert relative path")
  ("W" embark-save-relative-path "Save relative path")
  ("l" load-file "Load")
  ("b" byte-compile-file "Byte-compile")
  ("R" byte-recompile-directory "Byte-recompile directory"))
```

Examining the resulting `embark-file-map` seems to give the right result, but which-key doesn't show the descriptions. I'm not an expert on which-key (I installed this to see if I could get this to work!), do you know what I'm doing wrong?

**Comment by minad** [comment] 2020-12-30 00:55
Oh, interesting. You are really trying this :) One the one hand I like it since it is pretty, on the other hand it is sometimes useful to see command names. But you can always look it up in the embark keymap...

I will test it in my setup!

**Comment by oantolin** [comment] 2020-12-30 01:42
I used just (desc) because (desc . cmd) is supposed to very first that cmd is actually bound to whatever key it is before using desc.

**Comment by oantolin** [comment] 2020-12-30 05:13
I read a bit of the which-key source code: even though you give it the keymap as an argument it still looks keys up in the environment! (I didn't understand why, as soon as I found that I knew one possible fix for this problem and stopped reading.) That means that my macro is fine, but you need to call `which-key--show-map` like this:

```elisp
(setq embark-action-indicator
      (lambda (map)
        (let ((overriding-local-map map))
          (which-key--show-keymap "Embark" map))
        #'which-key--hide-popup-ignore-command)
      embark-become-indicator embark-action-indicator)
```

**Comment by minad** [comment] 2020-12-30 07:29
Maybe propose a fix to which-key? But the behavior could also be intensional?

**Comment by oantolin** [comment] 2020-12-30 12:58
I should try (a little bit) to figure out why they lookup the keys.

**Comment by minad** [comment] 2021-01-19 10:58
@oantolin It seems we may get menu item support in which-key, see https://github.com/justbur/emacs-which-key/pull/282. Then we don't have to use which-key pseudo keys here!

**Comment by minad** [comment] 2021-02-10 21:53
Good news: https://github.com/emacs-mirror/emacs/commit/21e475ea0c0d04ae7634f377ed64fe179388b133

**Comment by oantolin** [comment] 2021-02-10 21:57
I use `M-o` for `other-window`. (I used ace-window for a while, but soon realized that since I practically never have more than 3 windows, `other-window` is enough for me.)

**Comment by minad** [comment] 2021-02-10 22:04
Another reason to move to Emacs 28 ;) I have `M-o` bound to `ace-window` but I am also using it rarely. I just found the `M-o` removal while scrolling through the recent commits. I never really looked at the recent Emacs git history - there is a lot going on. It is amazing!

**Comment by oantolin** [comment] 2021-02-10 22:11
I'm pretty excited about the improvements for end-users in Emacs 28. The infrastructure improvements are bittersweet, however: I'll be tempted to use them, but won't be able to in my MELPA packages for a long time because I'll want to support Emacs 27 until, say, Ubuntu drops it or something. It's frustrating.

For example, did you see they are adding a variable that tracks the command that opened the minibuffer? Like `marginalia--this-command` or `embark--command`, but presumably without the bug that those two have.

**Comment by minad** [comment] 2021-02-10 22:18
> For example, did you see they are adding a variable that tracks the command that opened the minibuffer? Like marginalia--this-command or embark--command, but presumably without the bug that those two have.

Yes, I know. I wonder if there wouldn't have been a better solution which could be emulated somehow on the elisp level to make the transition easier. But this is a usual problem - it will take a long time until you profit from infrastructure improvements. But as I said in #151, I will at least drop Emacs 27 when Emacs 28 has been released. This is already an improvement over 26 it seems to me, given the 26 bugs and incompatibilities. So we should not be happy about 28, but about 27 actually :laughing:

**Comment by oantolin** [comment] 2021-02-10 22:22
By the way, is there an easy fix for the `marginalia--this-command`/`embark--command` problem? I think we haven't discussed it. The problem is that when a single command `foo-bar` prompts more that once, the variables correctly get set to `foo-bar` during the first minibuffer, but then during the second and later minibuffers they are set to whatever `RET` does, `selectrum-select-current-candidate` for you.

**Comment by minad** [comment] 2021-02-10 22:57
No we have not discussed this in detail. It seems to me that there is no easy solution for this, but maybe we can come up with something. I thought about it once when we first discussed the introduction of this new Emacs 28 variable, but to no success. It came up either here, on the Consult or on the Selectrum tracker.

**Closed** 2021-04-29 23:04 UTC
