### ISSUE TITLE
No popup help for embark-consult-search-map

### ISSUE THREAD

**Issue by hmelman** [oantolin/embark#215] opened 2021-05-03 19:59 UTC
I'm using embark with consult and have embark configured as shown in the wiki to use `which-key`.  `embark-consult.el` does:

    (define-key embark-general-map "C" embark-consult-search-map)

If I invoke `embark-act` (say on a symbol in a buffer), `which-key` shows me various key bindings.  `C` is listed last (I'm not sure why) and is shown as a prefix, great.  But if I type `C` I don't see `which-key` help showing me the next level of (search) commands.  If I then hit `C-h` for help, I see "Canceled" in the echo-area.  I'd like a way to get help on this keymap.

Emacs 27.2 (macport), latest melpa versions of these packages

**Comment by minad** [comment] 2021-05-03 20:35
Duplicate of #139 and #187.

**Comment by oantolin** [comment] 2021-05-03 23:23
I'm closing this as a duplicate.

**Closed by oantolin** 2021-05-03 23:23 UTC
