### ISSUE TITLE
embark-occur in consult-line gives empty embark occur buffer

### ISSUE THREAD

**Issue by hmelman** [oantolin/embark#78] opened 2021-01-01 17:17 UTC
Related to #77 without the mentioned selectrum config, if I do consult-line and invoke embark-occur, I get an empty embark-occur buffer.  embark-occur seems to work ok on other commands like describe-variable and find-file.

**Comment by oantolin** [comment] 2021-01-01 17:46
You mean with Selectrum but without the selectrum config in the wiki, right?

Oh, Selectrum... I guess today is the day I install it.

**Comment by hmelman** [comment] 2021-01-01 17:56
> You mean with Selectrum but without the selectrum config in the wiki, right?

Yes, that's what I meant.

**Comment by oantolin** [comment] 2021-01-01 17:56
I cannot reproduce this. Here's what I tried:

1. Run `emacs -Q`.
2. `M-x package-initialize`
3. `M-x selectrum-mode`
4. `M-: (define-key selectrum-minibuffer-map (kbd "C-;") #'embark-act-noexit)`
5. Open some file, run `M-x consult-line` and type `C-; O` to get the occur buffer. It is not empty, it contains the expected lines.

Please see if you can figure out how to reproduce this.

**Comment by hmelman** [comment] 2021-01-01 18:00
Hmmm.  It's a little hard for me to work from emacs -Q right now.  I did just try and found something odd.  My embark-act is bound globally, not on selectrum-minibuffer-map, if that matters.  I did consult-line in a markdown buffer and the occur worked fine.  I did the same thing in elisp buffer (searching for "defun") and it fails for me.  Nothing listed in the messages buffer.

**Comment by oantolin** [comment] 2021-01-01 18:16
Got it! I can reproduce this empty buffer now!

It didn't happen before because I wasn't typing anything at the `consult-line` prompt, in that case `embark-occur` did give me a buffer with all the lines.

I'm pretty sure this is what happens: without any integration, Embark occur gives you the candidates that the completion-styles think match, but we want Embark Occur to give the candidates Selectrum thinks match.

The default completion-styles, in particular don't include `subtring`, so basically nothing matches in `consult-line` except at the beginning of the line!

**Comment by oantolin** [comment] 2021-01-01 19:15
OK, closing this because the updated Embark integration on the Selectrum wiki should take care of it.

**Closed by oantolin** 2021-01-01 19:15 UTC
