### ISSUE TITLE
Setting command history when using embark-export

### ISSUE THREAD

**Issue by hmelman** [oantolin/embark#452] opened 2022-02-01 18:23 UTC
I'm not sure if this an issue with consult integration or a general issue with embark export.  If I run a `consult-grep` command (or similar) and then invoke `embark-act` and then `embark-export` I get the export buffer I expect and that's fine.  But, I think since I didn't terminate the `consult-grep` command, my input isn't saved in the command history in `consult--grep-history`.  So if I invoke `consult-grep` again and use `M-p` I don't see the last input I entered before doing `embark-export`.  It would be useful if I did.

**Comment by minad** [comment] 2022-02-01 18:52
I don't think in the case of `embark-export` anything should be done in general, since in this case you don't select a candidate. Therefore the input should not be preserved. Note that the minibuffer history is not an input history in general. Only a few Consult commands use it as input history (consult-grep/line etc).

However there is a related point to be made: In the case of actions which quit the minibuffer, Embark should probably store the candidate in the minibuffer-history-variable (as long as minibuffer-history-variable/=t, disabled history). The issue is that the history will then contain the candidate for commands like consult-grep/line, while the command actually expects the input.

So either Embark continues to do nothing, or starts to add selected candidates to the minibuffer history with the aforementioned problem for commands which abuse the history for input. Then I would have to change the history handling in Consult somehow, e.g., I could introduce a separate input history variable and hook it into the future history somehow. It will be a mess. I think it would be better if Embark then starts to distinguish input vs candidate histories. Unfortunately this is a concept which is unknown to Emacs (Emacs only knows candidate histories). Input histories are only used by Consult. It may make sense to introduce input histories for `completing-read`, but I am not going to propose it.

**Comment by minad** [comment] 2022-02-01 18:59
In the context of our [Uchronia](https://github.com/minad/uchronia) experiment, we explored separate input and candidate histories. But this turned out to be not important enough or it was too boring to pursue :shrug: 

Currently there exists a Vertico-specific stripped down version (vertico-repeat.el). Maybe it will see improvements in the future, see https://github.com/minad/vertico/issues/182. Not sure, but I believe that vertico-repeat also handles if Embark "prematurely" exists the minibuffer. So maybe vertico-repeat is a solution for you and for this specific problem?

**Comment by hmelman** [comment] 2022-02-01 20:59
> I don't think in the case of `embark-export` anything should be done in general, since in this case you don't select a candidate. Therefore the input should not be preserved. Note that the minibuffer history is not an input history in general. Only a few Consult commands use it as input history (`consult-grep` and `consult-line` etc).

Well I'd like in those cases (and a friend brought this up in the context of `consult-recoll`) to preserve the input when using `embark-export`.  In these searching contexts, I think it's common to collect the results and want to recreate or modify the search again and access via `M-p` is convenient and expected.  I'd like to see some way to have the collect commands store the input into `minibuffer-history-variable` maybe discriminated by category type?  So embark could store the input for `consult-grep` or `recoll-result` categories but not file or others.

I'm sure I don't know all the nuances in the distinction between a "minibuffer history" and an "input history" but I'm working on the assumption that it's about selecting a candidate in the `completing-read` case vs the input.  IIUC, in the other read commands the history includes input entered but not aborted and I think of `completing-read` history (possibly incorrectly)  it in those terms and not in candidate selected or not terms.  So when using   `M-x grep` I'll easily get to previous searches via `M-p` because I entered them as input.  I'd like the equivalent in the `consult-grep` and `embark-collect` idiom since it feels like a normal exit and not an aborted command.

I haven't looked at `vertico-repeat` and wasn't much of a user of `ivy-repeat` but AIUI I'd rather access this history via the specific command and not running the last vertico completion (I could be wrong).

I don't think I have an opinion yet on your related point of embark command that quits storing a selected candidate in the history.  I agree that sounds like a good thing, but I don't think I've come across an issue yet with current functionality, so I don't know if the need is real.

**Comment by oantolin** [comment] 2022-02-01 23:50
I think we probably only want the input stored for very few commands, probably only `consult-line`, `consult-grep` and the like. So my inclination is to just do it in `:before` advice on `embark-export`. Maybe if that feels too hacky, I can add an `embark-before-export-hook` (there is already an `embark-after-export-hook` that runs once the newly created export buffer is ready).

**Comment by oantolin** [comment] 2022-02-02 00:11
So I'm advising advising thusly:

```elisp
(defun store-input-for-consult ()
  (add-to-history
   (pcase embark--command
     ('consult-grep 'consult--grep-history)
     ('consult-line 'consult--line-history))
   (minibuffer-contents)))

(advice-add 'embark-export :before #'store-input-for-consult)
```

**Comment by oantolin** [comment] 2022-02-02 00:13
There is still @minad's other point, that most of the time a quitting `embark-act` should store the candidate in the value of `minibuffer-history-variable` (when it is not `t`). Though if you run `embark-export` from `embark-act` from `consult-grep` that's not what you want happening.

Also, I'm probably missing a few (p)cases in the code above.

**Comment by minad** [comment] 2022-02-02 00:19
I don't think we should add a half baked solution which only works for `embark-export`. Ideally we store the candidate when acting and quitting and also handle the input history. We could check `minibuffer-history-variable` against a few known input history variables (which could be configured by embark-consult.el).

**Comment by oantolin** [comment] 2022-02-02 00:21
Well, you want the input stored when you use `embark-export` whether or not you ran `embark-export` from `embark-act`, right?

**Comment by oantolin** [comment] 2022-02-02 00:22
Plus I'm not suggesting adding anything to any package, I'm suggesting users who want special behavior for `embark-export` when used with a consult search command do it in their personal configuration via advice.

**Comment by minad** [comment] 2022-02-02 00:23
> Well, you want the input stored when you use embark-export whether or not you ran embark-export from embark-act, right?

That's right. But `embark-export` has explicit quitting logic like `embark-act`, so the handling should be there.

Also, adding and `embark-before-export-hook` feels rather ad-hoc. The after export hook makes sense since it allows you to manipulate the resulting buffer, but the before hook feels artificial. There are no equivalents for collect-snapshot.

> Plus I'm not suggesting adding anything to any package, I'm suggesting users who want special behavior for embark-export when used with a consult search command do it in their personal configuration via advice.

Yes, this is probably the best solution for now.

**Comment by oantolin** [comment] 2022-02-02 00:26
Input histories are a Consult invention, so I'd be more comfortable with all Embark business to do with input histories to be completely contained in embark-consult. In particular, I don't think I'd want any code in Embark to look at some `embark-commands-which-use-input-history` variable, even if that variable is only set in embark-consult.

**Comment by oantolin** [comment] 2022-02-02 00:27
I agree with the before export hook feeling artificial.

**Comment by oantolin** [comment] 2022-02-02 00:30
How about this? i think all quitting is handled by `embark--quit-and-run`, we can add storing the candidate in the history variable to that function. It will retrieve the candidate via a new helper `embark--minibuffer-candidate` (which just runs `embark--targets` in the minibuffer and returns the first element). Then in embark-consult we advise `embark--minibuffer-candidate` to use the minibuffer input instead in the appropriate cases.

**Comment by oantolin** [comment] 2022-02-02 00:36
Is there a way to get a hold of the `:history` argument of `consult--read` while it is running? Or do I have to write a list of input-history commands in embark-consult?

**Comment by oantolin** [comment] 2022-02-02 00:44
Now that I think about it, it's not really clear which history variable should receive the candidate! Say I run the `foo` command and then run `baz` as a quitting action, should the candidate be added to `foo`'s history or to `baz`'s? I mean `baz` is the command that really operated on the candidate... I guess most often since `foo` and `baz` probably act on the same type of candidates, they will share a history, but sometimes they might not.

**Comment by hmelman** [comment] 2022-02-02 01:48
So this bug is now about two things.  My original request for the input to be in the history when `embark-export` is run (and probably rightfully generalized to all `embark-collect`-like commands run on all `consult-grep`-like commands which to me includes `consult-find`-like commands).  I'd love an official solution, but even working suggested code in a wiki would be very helpful.

There's also minad's suggestion about embark storing candidates in history on quit commands.

I'm not sure which you were referring to when you wrote "Input histories are a Consult invention" but I want to clarify.  I think you mean that builtin emacs commands don't do this, and I'll assume that's correct.  But at least in what I originally asked for, I think `counsel-grep` and `helm-grep` commands do support this idea, that if you save the buffer in their equivalent of `embark-collect` they remember the previous input and make it available via `M-p`.  I could be wrong (a friend says `counsel-recoll` did and it matches my memory of it) but it's that equivalent functionality I'm looking for if it's possible given the api constraints consult and embark have.  And AIUI the `:history` param to `consult--read` is basically equivalent to the same in ivy and helm functions and in `completing-read`, so I'm confused by you saying they're a consult invention.  Am I misunderstanding?

**Comment by oantolin** [comment] 2022-02-02 02:20
This is the distinction you mentioned you weren't entirely sure about, @hmelman. During a minibuffer completion session you have what you type at the minibuffer, the minibuffer contents, and then you have the selected candidate: the string that the command you called would actually act upon if you press RET. So say I'm using Vertico or Icomplete and I run `find-file`. Maybe I type `f.t` and that matches, say `file1.txt` and `file2.txt`. I could move among the candidates to select `file2.txt` and press `RET` to open it. The minibuffer contents are just `f.t`, but the selected candidate is `file2.txt`.

Now the distinction: what the Emacs history mechanism does is store the selected candidate, `file2.txt`; but Consult has this idea that for search commands like `consult-line` or `consult-grep`, it's better to store the "input", the minibuffer contents, since that's the search term and repeating it will repeat the search. So Consult's internal `consult--read` function let's you specify whether you want the candidate stored in the history or the input, for the candidate (which is normal Emacs behavior), you pass `:history 'my-history-variable` to `consult--read`, but to request this new "store input" behavior you instead pass `:history '(:input my-history-variable`.

So I'd like embark to cooperate with the normal Emacs history mechanism and not know anything about Consult's idea that some commands repurpose the history mechanism to instead store the minibuffer contents; and I'd like embark-consult to tweak embark's behavior for the Consult commands that use `:input`. Does that make sense? The idea is that Embark is only allowed to hard-code behavior for Emacs built-ins, and embark-consult is allowed to hard-code behavior for Consult commands.

**Comment by hmelman** [comment] 2022-02-02 03:10
> This is the distinction you mentioned you weren't entirely sure about, @hmelman. During a minibuffer completion session you have what you type at the minibuffer, the minibuffer contents, and then you have the selected candidate: the string that the command you called would actually act upon if you press RET. So say I'm using Vertico or Icomplete and I run `find-file`. Maybe I type `f.t` and that matches, say `file1.txt` and `file2.txt`. I could move among the candidates to select `file2.txt` and press `RET` to open it. The minibuffer contents are just `f.t`, but the selected candidate is `file2.txt`.

Yes input vs candidate. 👍 

> Now the distinction: what the Emacs history mechanism does is store the selected candidate, `file2.txt`; but Consult has this idea that for search commands like `consult-line` or `consult-grep`, it's better to store the "input", the minibuffer contents, since that's the search term and repeating it will repeat the search. So Consult's internal `consult--read` function let's you specify whether you want the candidate stored in the history or the input; to request the candidate be stored (which is the normal Emacs behavior), you pass `:history 'my-history-variable` to `consult--read`, but to request this new "store input" behavior you instead pass `:history '(:input my-history-variable)`.

Thanks, I was unaware of this `:input` distinction in `consult--read`, it would be great if consult.el documented this.

FWIW I realized the builtin emacs does have an example of history storing the input, `isearch`.

> So I'd like embark to cooperate with the normal Emacs history mechanism and not know anything about Consult's idea that some commands repurpose the history mechanism to instead store the minibuffer contents; and I'd like embark-consult to tweak embark's behavior for the Consult commands that use `:input`. Does that make sense? The idea is that Embark is only allowed to hard-code behavior for Emacs built-ins, and embark-consult is allowed to hard-code behavior for Consult commands.

Yeah, totally makes sense and it's what I figured you guys were discussing, I just couldn't quite follow along.  I was wondering why you two weren't mentioning my suggestion of using categories, but it's because `:input` is a better indicator.  And your use of "minibuffer contents" to mean "input" confused me, but I understand it now (at first I thought this was the candidates).

I see that embark has ivy integration, does it have a similar explicit mechanism for storing input in the history instead of candidates?  I've only used embark with consult and I'm not sure if `embark-collect` works with ivy or if you refer users to `ivy-occur`?

**Comment by minad** [comment] 2022-02-02 11:35
I didn't follow along entirely, but my suggestion would be to do nothing for now, except maybe refactorings which are valuable on their own and which make adding advices in the user configuration easier. I am not sure I will keep the input history mechanism as is for ever or if I will change it again at some point. While I like that Consult search commands store the input instead of the candidate it goes a bit against the usual Emacs behavior, which leads to problems down the road. And in any case if we don't find a cleaner solution in the long term, I agree that any such Consult-specialties should of course be present in embark-consult.el only and not affect embark.el.

**Comment by oantolin** [comment] 2022-02-02 16:18
OK, so I think for now the following is good enough:

```elisp
(defun store-input-for-consult ()
  (when (memq minibuffer-history-variable
              '(consult--grep-history
                consult--line-history
                consult--find-history
                consult--man-history))
    (add-to-history minibuffer-history-variable (minibuffer-contents))))

(advice-add 'embark-export :before #'store-input-for-consult)
(advice-add 'embark-collect-snapshot :before #'store-input-for-consult)
```

@hmelman can directly add that to his configuration. I'll close this issue, but of course we can continue discussing.

For now I don't think I'll do anything about having quitting actions store history, since I don't think anyone has missed that behavior, and it's not clear whether the candidate should be stored in the history for the action or the history for the command that opened the minibuffer (or both?).

Also, I want to answer a few of @hmelman's comments and questions:

> Thanks, I was unaware of this :input distinction in consult--read, it would be great if consult.el documented this.

I doubt @minad wants it mentioned in the manual, he likely considers it an implementation detail. Maybe the docstring for `consult--read` should mention it however, since that command is internal too. A soul brave enough to use `consult--read` with its lack of guaranties, deserves t know about `:input`.

> FWIW I realized the builtin emacs does have an example of history storing the input, isearch.

Ah, true, but a little special because isearch does not use completing-read, so there really aren't any candidates it could be storing instead of the input!

> I see that embark has ivy integration, does it have a similar explicit mechanism for storing input in the history instead of candidates?

I don't remember if Ivy has such a mechanism, I think maybe commands like `swiper` do store the input, but I don't remember for sure and don't exactly how it's done. I have Ivy installed but I use it exclusively for testing the Embark and Orderless integrations. 😛 I don't have Swiper installed at all.

> I've only used embark with consult and I'm not sure if embark-collect works with ivy or if you refer users to ivy-occur?

It does work with Ivy when Ivy is just being used to override `completing-read`, that is, for commands that use `completing-read` (even elaborate ones like the Consult commands), Embark does work if you are using Ivy for completion.

But as I recall commands in Swiper and Counsel make a fancier use of Ivy and Embark doesn't quite work with some of those. I'm pretty sure Embark did something weird with `swiper` candidates, and I don't know how well it works with Counsel commands. Embark has Ivy integration because someone requested it (I can't remember who right now, maybe it was @astoff), and that person probably knows how well Embark works with Swiper and Counsel. Maybe I should test that myself someday.

**Closed by oantolin** 2022-02-02 16:18 UTC

**Comment by hmelman** [comment] 2022-02-02 16:30
Thanks, I'll try the suggested code.

> > Thanks, I was unaware of this `:input` distinction in `consult--read`, it would be great if `consult.el` documented this.
> 
> I doubt @minad wants it mentioned in the manual, he likely considers it an implementation detail. Maybe the docstring for `consult--read` should mention it however, since that command is internal too. A soul brave enough to use `consult--read` with its lack of guaranties, deserves t know about `:input`.

I know that `consult--read` is internal, I was just hoping for a comment in `consult.el` though I think this would be appropriate in the docstring.  Since consult doesn't implement all the commands that other packages like counsel and helm do, and encourages people write their own, (comment) hints of the use of `consult--read` would be helpful.

**Comment by astoff** [comment] 2022-02-03 14:34
> Embark has Ivy integration because someone requested it (I can't remember who right now, maybe it was @astoff), and that person probably knows how well Embark works with Swiper and Counsel

I think your supposition about the requester is correct, but I haven't used Ivy et caterva in a long time...

Anyway, this is an interesting discussion. I have an advice on my isearch so that the search string is recorded to history also when I abort/cancel the search. Sometimes I miss this behavior in `consult-grep`. I guess I would want `C-g` to record history on every Consult command with `:input` history? I'd have to try it out to be sure.

**Comment by hmelman** [comment] 2022-02-28 18:58
@oantolin Did some calling sequence in embark-collect-snapshot change recently?  Now when I do: 

- `C-x 8 RET` (`insert-char`) 
- type `check` to see a list of check marks
- `s-;` (`embark-act`)
- `S` (`embark-collect-snapshot`) 
 
I get an error that my function, the `store-input-for-consult` above, is called with the wrong number of arguments.  Making the signature `(&rest args)` solves it and the value of `args` is `(nil)`, but I wonder what the correct thing is.

Emacs 27.2 macport and the latest versions of embark, consult, vertigo, marginalia from melpa.

**Comment by oantolin** [comment] 2022-02-28 21:13
No recent changes, @hmelman: `embark-collect-snapshot` has always had an optional argument. So the code above has always had a bug with `embark-collect-snapshot`! I think I must have only tested with `embark-export`.

Your modification of making the signature `&rest args` is the correct way to handle this.

**Comment by hmelman** [comment] 2022-03-29 15:50
I just want to update, the code [above](https://github.com/oantolin/embark/issues/452#issuecomment-1028109889) works well for me, but as of March 2022, `embark-collect-snapshot` changed to `embark-collect` so the last line, the advice has to change to:

```elisp
(advice-add 'embark-collect :before #'store-input-for-consult)
```
