### ISSUE TITLE
How do I add Dired buffers to a custom Embark keymap?

### ISSUE THREAD

**Issue by grolongo** [oantolin/embark#688] opened 2023-11-28 12:50 UTC
Hi and thank you for Embark!

I'm trying to use a custom Embark keymap but I don't know how to "link it" to Dired buffers.

I've made a simple example:
```elisp
(defvar-keymap embark-dired-map
  :doc "Embark keymap for Dired buffers."
  "d" #'my-function)

(add-to-list 'embark-keymap-alist '(dired-mode embark-dired-map))
```

But when I call `embark-act` in a Dired buffer, the default `embark-general-map` is called. I could add `#'my-function` directly to `embark-general-map` but I want a custom mapping with only specific functions I have.

**Comment by oantolin** [comment] 2023-11-28 22:13
Embark decides which key bindings to activate by looking at the target of the actions. What target do you wish to run your `my-function` on? Once you've decided that, if it is not a target built-in to Embark you will also need to add a target finder to Embark and register `embark-dired-map` in `embark-keymap-alist` as the keymap to use for that type of target.

So is there some particular text in the dired buffer you will put the cursor on before you want to run `my-function`? If the action makes no use of any particular target and you just want to run it in dired buffers (and not at any particular location within the buffers), then maybe Embark is not the best tool for this and a simple keybinding in `dired-mode-map` would be better?

**Comment by grolongo** [comment] 2023-11-28 23:36
> Embark decides which key bindings to activate by looking at the target of the actions.  

This is something I understand better now. Thank you. I thought this was more about any symbol from the mode it is in.

>What target do you wish to run your my-function on?  

Simply marked file(s) in Dired.  

For example I have a simple function that uses ffmpeg to convert a webm to a mp4. It does it for a single marked file in Dired. I'm calling the function through M-x.  

I was thinking of "enhancing" that function to do it on each marked file(s) in Dired, by introducing `embark-dired-candidates` that I found in your package.  

Also, since I have multiple little functions like this that operate on files from Dired, I was thinking of putting them all under an Embark keymap for quick access instead of having to use M-x.  

Now as I understand, I should add these functions under `embark-file-map`, if I'm not mistaken. But is it possible to keep the default ones as well? With the use-package syntax, this:

`:bind (:map embark-file-map ("f" . #'my-function)`

removes all the originals.

**Comment by oantolin** [comment] 2023-11-29 01:46
> Now as I understand, I should add these functions under embark-file-map, if I'm not mistaken.

Correct.

> But is it possible to keep the default ones as well? With the use-package syntax, this: `:bind (:map embark-file-map ("f" . #'my-function)` removes all the originals.

It is definitely possible. In that example you have overwritten the default bindings for `f`, but if you choose non-conflicting bindings you should be able to keep the default bindings too. If that line "removes all the originals", maybe the problem is that the binding is defined before `embark-file-map` is loaded and thus a brand new `embark-file-map` is created? Just assign the binding in `(use-package embark ...)` or, if you want to put it in a different `use-package` call, then do it `:after embark` is already loaded.

> I was thinking of "enhancing" that function to do it on each marked file(s) in Dired, by introducing `embark-dired-candidates` that I found in your package.

I see. This is a good idea. I'm not sure exactly how you are going about it, but what I would recommend is writing the function so it takes a single argument that is a list of strings representing file names. Here's an example that converts a bunch of images to a single multipage PDF using the `convert` command line tool:

```elisp
(defun multipage-pdf (files)
  "Convert multiple images FILES to a multipage PDF.
Prompts for the output file name."
  (let ((pdf (expand-file-name (read-file-name "PDF output file: "))))
    (apply #'start-process "*conversion*" "*conversion*" "convert"
           (append (mapcar #'expand-file-name files) (list pdf)))))

;; Tell embark your function operates on multiple files at once
;; (if you don't do this embark will assume you want it to loop
;; over the list of files and call the function for each one):
(add-to-list 'embark-multitarget-actions #'multipage-pdf)

```

Then, if you bind that to `p` in `embark-file-map`, you can run it on a single file with `embark-act` or on multiple files with `embark-act-all`. Say you bind `embark-act` to `C-.`. You can convert the file at point with `C-. p`, or use `C-. A p` to act on the currently marked files in dired (or, if none are marked, on all files shown in the dired buffer). Here `A` is bound to `embark-act-all` in `embark-general-map`.

The advantage of this is that you don't need to be in dired buffers to use those actions: for example, if you have a directory of jpg files in `~/pages/` and what to make a single PDF out of them you could run `find-file`, navigate to that directory and use `C-. A p`.

I'll close this issue, but please let me know if you have any further questions.

**Comment by oantolin** [comment] 2023-11-29 02:00
> For example I have a simple function that uses ffmpeg to convert a webm to a mp4. It does it for a single marked file in Dired. I'm calling the function through M-x.

If that function is written to convert a single file, then *don't* add it to `embark-multitarget-actions` and then if you use `embark-act-all` to act on multiple files, Embark will loop over the list for you. The example I showed above does handle multiple files at once (to make them into pages of a single PDF), which is why it makes sense to add that one to

**Closed** 2023-11-29 02:23 UTC
