### ISSUE TITLE
Handling of `g` binding in `embark-export`

### ISSUE THREAD

**Issue by purcell** [oantolin/embark#171] opened 2021-02-26 01:23 UTC
`g` usually connotes `refresh`, and indeed I used to use this in `ivy-occur` to refresh the ripgrep results in an occur buffer after making changes. In `embark-export` buffers, which are in grep-mode, `g` invokes "recompile", which will generally run a completely different command. I wonder if there's a way to handle this and make refresh possible in embark...

**Comment by oantolin** [comment] 2021-02-26 11:51
I'd love to have this feature too. Also for the occur export for `consult-line`. Currently the necessary information to regenerate the list is not stored, but it would be fairly easy to do so. I'll work on it when I get the chance.

Up to now this has been one of the main distinctions between embark collect and export: collect buffers have a working revert. But even for collect buffers, revert only works while the buffer you called `embark-collect-{snapshot,live}` from is still live. So in the case of calling `embark-collect-snapshot` from the minibuffer (the most common case to call it from!) doesn't actually have a working revert either.

**Comment by manuel-uberti** [comment] 2021-03-03 14:25
Oh, I was about to open an issue for this. Thank you @purcell for doing it first. :)

**Comment by DamienCassou** [comment] 2021-05-31 12:20
I would also love that and made some research:

- grep-mode inherits from compilation-mode.
- It seems like setting the `compilation-arguments` variable in the grep buffer would be enough to make `g` run grep with the same arguments again.
- `embark-consult-export-grep` just take candidates as input: the grep command and arguments got lost midway. I don't know how to propagate this information to the embark framework.
- `ivy.el` doesn't use the `compilation-arguments` but instead binds `g` to `ivy-occur-revert-buffer` and the initial buffer is created with `ivy-occur`.

**Comment by dschrempf** [comment] 2022-03-28 09:50
Has there been any progress on this? I keep getting compilation errors because I press `g r` in `Embark Export Grep` buffers :-).

**Comment by dschrempf** [comment] 2022-03-28 09:54
Not sure if this fits here, but `q` should probably also close the buffer and not define a key macro.

**Comment by minad** [comment] 2022-03-28 15:20
@dschrempf I think there has been progress recently. @oantolin simplified the Embark collect/export infrastructure greatly, which should help in picking up this issue again. However I am not aware of anyone working on this particular issue currently. I would also like to have this feature. It would be nice to have the ability to refresh the buffer after making edits. This affects in particular consult-line and consult-grep buffers. I guess @oantolin would also appreciate contributions, if you are interested in digging into the Embark code base. :)

**Comment by oantolin** [comment] 2022-03-28 15:48
I was going to say what @minad said, about the recent simplification probably helping. I do want to work on this but haven't found the time. One would need to store a `revert-buffer-function` that does the right thing: for export from a minibuffer, it should rerun the command that opened the minibuffer, retype the minibuffer contents, wait a configurable delay (for async searches like consult-grep), then gather the new candidates; for export from a non-mini buffer, it can probably just rerun the candidate collector.

**Comment by oantolin** [comment] 2022-04-04 20:32
I pushed an initial implementation that doesn't work in all cases, but you can try it out with dired export (rename a file, and revert to see the effect), or with `consult-line`. This initial implementation does *not* cover the case of exporting from `consult-grep` (or any async consult search command). See the commit message for more details.

**Comment by oantolin** [comment] 2022-04-04 23:49
I've fixed the jumping windows problem and now reverting an export buffer reuses whatever windows currently display it. Now the main thing remaining is making this work with `consult-grep` and other async search commands.

**Comment by oantolin** [comment] 2022-04-05 04:17
OK, a working prototype is available! b57c947f20dc36faff7a43076b9a3b0358f87921 To handle consult async searches, I just wait for the little star to turn into a colon. 🤣 Is there anything better I could do, @minad?

**Comment by oantolin** [comment] 2022-04-05 11:49
Quick updates:
- I added revert support for dired buffers that came from `consult-find` (thanks @minad for reminding me I had forgotten to do that).
-  `g` is now bound to `revert-buffer` in exported grep buffers (`revert-buffer` already worked there, but `g` was bound to `recompile` as @purcell pointed out).

**Comment by minad** [comment] 2022-04-06 04:10
`embark-collect-mode` buffers also need a proper revert function. In a `consult-grep` snapshot buffer revert does not seem to work.

**Comment by oantolin** [comment] 2022-04-06 04:53
Yes, I can confirm reverting an embark collect buffer is not supposed to work yet: these changes only apply to embark export buffers so far. I need to think a bit about the collect case, since embark-live already uses the revert machinery and expects it to behave a certain way.

Also, the collect revert function can be much less hacky since we control buffer creation in that case. Most of the exporters use some Emacs function that creates and display a buffer for you whether you want it or not, you can't say: "please just fill in this pre-existing buffer". But we can do that with collect.

On the other hand maybe the best thing would be to make collect and export even more similar. In fact, I could imagine collect becoming just a default exporter...

**Comment by dschrempf** [comment] 2022-04-06 13:12
To be honest, I don't really understing the difference between collect and export (there are different keybindings and such, but I don't get the purpose).

**Comment by dschrempf** [comment] 2022-04-06 16:36
I see, thank you for the explanation. I usually use `export`, but I understand now why you may want to keep both.

**Comment by minad** [comment] 2022-04-11 17:54
*Copying my comment from https://github.com/minad/marginalia/issues/136#issuecomment-1095343734*

-------

@oantolin Yes, it would be nice to solve the revert support in Embark. I don't consider the group-function and some other issues as important. These are more gimmicks and could go as well into another version. I think it is most important to fix bugs and some rough edges.

What do you think about solving the revert problem in a simpler way - what if we don't support reverting for Consult Async commands, but instead do the following?

1. Close the grep/snapshot buffer
2. Restart the command with the input
3. Let the user do the rest

This special behavior could be configurable per command or completion category via an exclusion configuration variable. For normal synchronous completion commands revert of snapshot/export should simply work (there shouldn't be an issue?). The advantage of this is also that one could reedit the input. I think it makes sense to provide two commands anyway

1. revert-buffer
2. embark-collect-edit/embark-export-edit

and for async commands revert-buffer would just be the same as embark-collect-edit/embark-export-edit.

**Comment by oantolin** [comment] 2022-04-11 19:15
That sounds pretty reasonable to me, and it's certainly easy to implement. My only worry is that it might be a case of shifting work onto the users to make the implementation easier. If the vast majority of times, after the command is rerun and the input reentered, people are just going to wait for the search to finish and then export again, it would be nice to automate that.

In another matter, if we do go this route there is also a configurationless option: to treat sync and async the same, in all cases just rerun the command and reenter the input, then less users do the rest. Would that be terrible?

**Comment by minad** [comment] 2022-04-11 19:28
> My only worry is that it might be a case of shifting work onto the users to make the implementation easier. If the vast majority of times, after the command is rerun and the input reentered, people are just going to wait for the search to finish and then export again, it would be nice to automate that.

Yes, however in the case of async commands there are simply too many downsides and it seems to me that there are quite a few arguments against it.

1. We need special coordination between Consult and Embark. Currently we don't have this, we rely only on completion categories and the data attached to the candidates, which is a protocol which is easy to understand.
2. Reverting buffers for async commands is not well defined since commands don't have to stop producing candidates. Commands could continuously produce candidates forever, the Consult API does not prevent that.
3. The minibuffer popping up is annoying and looks like a glitch. This only matters for Vertico or Mct and it wouldn't affect the manual default UI. We could try to enforce that the default UI is used during revert. But then we would need an additional progress report, which is adhoc complexity.
4. In the case of Vertico, there is vertico-repeat. Of course this is not an exact substitute but still helps.
5. This is only a personal preference but I am willing to sacrifice minor conveniences for more conceptual clarity. Restarting a command and allowing the user to do the rest is simple and works in all scenarios. On the other hand, revert for async commands requires a rather ad-hoc implementation.
6. You can define arbitrary candidate collectors. How to restart, revert those? It seems to me that the revert feature just doesn't fit well into the Embark/Consult framework.

> In another matter, if we do go this route there is also a configurationless option: to treat sync and async the same, in all cases just rerun the command and reenter the input, then less users do the rest. Would that be terrible?

No, for me it would be fine. I mean we have to compare with the status quo (or the status before the current incomplete revert implementation).

**Comment by oantolin** [comment] 2022-04-11 19:42
> The minibuffer popping up is annoying and looks like a glitch.

No, no, it's a very tall progress bar! 😛 

But seriously, I don't like it either, and certainly if we redefine "revert" to just mean "rerun the command and reenter the input", then the minbuffer popping up would be completely reasonable.

**Comment by minad** [comment] 2022-04-11 19:46
> But seriously, I don't like it either, and certainly if we redefine "revert" to just mean "rerun the command and reenter the input", then the minbuffer popping up would be completely reasonable.

Exactly. We just redefine revert to mean something else which makes sense for Embark/Consult :)

**Comment by oantolin** [comment] 2022-04-11 19:50
I like this proposal, and think I'd start without any configuration options, those can always be added later.

**Comment by oantolin** [comment] 2022-04-13 20:10
Ok, I think this should be good to go. I implemented @minad's suggestion for simpler revert semantics, for both `embark-export` and `embark-collect`:

- If you ran `embark-export/collect` from the minibuffer, running `revert-buffer` in the export/collect buffer kills the buffer, reruns the command that had opened the minibuffer and re-enters the input that was in the minibuffer at the time you exported/collected.

- If you ran `embark-export/collect` from a non-mini buffer, `rever-buffer` just runs it again.

I like the functionality, it feels straightforward and uniform. And I like being able to tweak the "search terms" (minibuffer contents) before re-exporting.

Please test and report any problems.

**Comment by minad** [comment] 2022-04-13 20:20
Great, thanks! I will try it soon.

**Comment by oantolin** [comment] 2022-04-13 20:22
You'll also like @minad, that I removed the `embark-collect--candidates` variable. 😛

**Comment by minad** [comment] 2022-04-13 20:25
Sure all simplifications are welcome! 😄

**Comment by minad** [comment] 2022-04-13 20:27
It seems as if you got rid of a lot of global state. Very nice :)

**Comment by minad** [comment] 2022-04-13 20:38
I tested this and it works great. I like this behavior, it is simple and coherent. I like that there is a way back from the collect/export buffer to the completion command. Exporting again from there is not a big deal. However I wonder if we should print a message?

- For revert of normal buffer exports: "Reverting buffer..."
- For going back to minibuffer: "Restarting completion command..."

**Comment by minad** [comment] 2022-04-13 20:40
It should also be possible to implement a poor mans revert function based on this base functionality? Not as part of Embark but we could put it into the wiki.

1. Open the minibuffer
2. Wait for a second (or even use polling of the consult-grep prompt)
3. Run export/collect

**Comment by oantolin** [comment] 2022-04-13 20:44
Good idea, specially for the normal buffer case, where it's not clear something happened otherwise.

**Comment by oantolin** [comment] 2022-04-13 20:45
Although, the usual Emacs behavior seems to be to revert without any message at all (except if you are prompted for confirmation, of course). I just tested a normal file, a dired buffer and a help buffer.

**Comment by oantolin** [comment] 2022-04-13 20:47
Weird: `revert-buffer` doesn't print a message (if you are in a no-confirmation case) but `revert-buffer-quick` does.

**Comment by oantolin** [comment] 2022-04-13 20:51
Oh, I missed your other comment, about the poor man's revert function, @minad. That could definitely be done, but I'd wait to see if there's demand. I wasn't sure I'd like this behavior but now I'm sold, maybe others will also find they don't need a full revert.

**Comment by minad** [comment] 2022-04-13 20:57
> Weird: revert-buffer doesn't print a message (if you are in a no-confirmation case) but revert-buffer-quick does.

Oh okay, maybe I am already accustomed to `C-x x g` :)

> Oh, I missed your other comment, about the poor man's revert function, @minad. That could definitely be done, but I'd wait to see if there's demand. I wasn't sure I'd like this behavior but now I'm sold, maybe others will also find they don't need a full revert.

Sure. I just meant that with the current facilities we could still easily implement this on top.

> Good idea, specially for the normal buffer case, where it's not clear something happened otherwise.

I thought that it could also be useful in the minibuffer case just to explain what is going on, since it deviates from usual buffer revert. But it is probably sufficient to document this well in the docstrings or the readme. Furthermore a message will get annoying anyway. Generally Emacs is way to noisy for me and I suppress a lot of messages. So maybe I shouldn't propose adding more. But I think a `ding` here and there would certainly be appreciated by most of the Embark user base. :-P

**Comment by oantolin** [comment] 2022-04-13 21:46
Thanks for mentioning documentation, I had forgotten! ab778510d5db9935a2d436b13d98c47b824172ee

**Comment by jaor** [comment] 2022-04-13 21:49
On Wed, Apr 13 2022, Omar Antolín Camarena wrote:

> Oh, I missed your other comment, about the poor man's revert function,
> @minad. That could definitely be done, but I'd wait to see if there's
> demand.

fwiw, the first thing i'll do is implementing a revert command like that
(recomputing the collect buffer in one keystroke): that's what i want in
most of the time.  and a C-u prefix will give me the variant reopening
the minibuffer for the remaining cases (i'd provide that behaviour
directly in embark if it were my package, perhaps via C-u, but this is
emacs, so we can both be opinionated in different directions at the same
time! :))

**Comment by oantolin** [comment] 2022-04-13 21:55
Mmh. Now that I removed the one-shot revert from embark-consult, I am reluctant to reintroduce it. It was hacky and probably a little unreliable, basically I don't want to give it any support. How about I reintroduce the hook it required and put the necessary configuration on the wiki, @jaor?

**Comment by minad** [comment] 2022-04-13 22:04
@oantolin Is it even necessary to introduce a hook? Is it not sufficient to write something like this?

~~~ elisp
(defun embark-revert ()
  (interactive)
  (run-at-time 0 nil #'message "Reverting...")
  (run-at-time
   1 nil ;; Instead of a fixed time one could use polling here
   (lambda ()
     (when-let (win (active-minibuffer-window))
       (with-selected-window win
         (embark-export))))) ;; embark-export or embark-collect, determine based on buffer name?
  (revert-buffer))
~~~

**Comment by oantolin** [comment] 2022-04-13 22:07
Oh, right! Very nice @minad!

We can refine that function a bit and toss it on the wiki: add the polling for consult async search commands and use `embark-collect` for `embark-collect-mode` buffers and `embark-export` for all others.

**Comment by minad** [comment] 2022-04-13 22:09
> We can refine that function a bit and toss it on the wiki: add the polling for consult async search commands and use embark-collect for embark-collect-mode buffers and embark-export for all others.

Yes, this is what I meant by "poor man's implementation" based on the more basic functionality we have now in Embark. It is a nicely stacked design :)

**Comment by oantolin** [comment] 2022-04-14 15:59
@dschrempf I forgot one case in which you might prefer embark collect to embark export even if there is a special major mode that export would use! You may want to mark some candidates and use `embark-act-all` on them. Now, you wouldn't do this with files or buffers, because then export produces dired or ibuffer buffers, both of which let you mark items and run commands on them. But many export buffers do not have candidates marking functionality: occur, grep, apropos and customize buffers don't for example.

A case that just came up for me was that I wanted to insert a bunch of face names in an email message composition buffer, split into two different locations in the message. So I ran `describe-face`, typed a pattern that matched all the faces I needed and ran `embark-collect`. In the collect buffer I marked all the faces I wanted to insert at the first spot in the email and ran `embark-act-all`, `embark-insert`. Then I moved in the email buffer to the second spot where I wanted the other faces, returned to the embark collect buffer, toggled the marks and again used `embark-act-all`, `embark-insert`. It was much faster to do than to describe here!

In Embark's default configuration faces export to a customize buffer, which is great for tweaking the faces (o even just reading their docstrings!), but in this case I needed the ability to mark a subset of them and so went with `embark-collect`.

**Comment by dschrempf** [comment] 2022-04-15 06:27
Thank you, that makes sense. Collect seems especially useful when the major mode used by embark does not allow marking.

**Comment by oantolin** [comment] 2022-04-15 16:58
After using this a couple of days, I'm really enjoying this "revert means rerun" functionality. It feels like a good UI for two operations: reverting and rerunning with slightly modified input. There are, of course, alternatives such as (1) offer two separate commands, (2) offer a command that does one thing or the other depending on the prefix argument. But what I like about the current choice is that it has late binding: you first press `g` and *later* decide whether to just reexport or to tweak the input first. You get to see the updated results *before* deciding whether you want to change the input, which I really like.

**Comment by minad** [comment] 2022-04-19 20:16
I observed one problem in exported grep buffers. After switching to wgrep and back, the keybinding of `g` is reset to `recompile`. Did you observe this behavior too?

**Comment by oantolin** [comment] 2022-04-19 20:30
Good catch, @minad! It was an easy fix.

**Comment by oantolin** [comment] 2022-05-03 00:15
I'm closing this issue because I feel satisfied with the current functionality, but please feel free to continue the discussion or to reopen.

**Closed** 2022-05-03 00:18 UTC

**Comment by jaor** [comment] 2022-10-11 07:58
> How about I reintroduce the hook it required and put the necessary
> configuration on the wiki, @jaor?

works for me, thanks!

**Comment by mpereira** [comment] 2023-03-21 16:46
Was there a regression on this fix? Or maybe I'm doing something incorrectly.

1. Run `M-x consult-grep` or `M-x consult-ripgrep`
2. Run `embark-act` on the candidates buffer
3. Press `E` for `embark-export`, get "Grep mode" buffer
4. `g r` is mapped to `recompile` which tries to run `make -k` instead of recomputing and re-rendering grep or ripgrep results
5. `M-x revert-buffer` says `revert-buffer--default: Buffer does not seem to be associated with any file`

`M-x embark-rerun-collect-or-export` correctly re-runs the grep or ripgrep search and recreates the candidates buffer, but I'm looking for a way to recreate the "Grep mode" buffer.

| Software  | Version |
|-----------|---------|
| macOS     | 13.2    |
| Emacs     | 29.0.60 |
| Embark    | 0.21.1  |
| Consult   | 0.33    |

**Comment by dschrempf** [comment] 2023-03-21 19:10
I think this is not a regression. It is expected behavior. I quote from above:

> After using this a couple of days, I'm really enjoying this "revert means rerun" functionality. It feels like a good UI for two operations: reverting and rerunning with slightly modified input. There are, of course, alternatives such as (1) offer two separate commands, (2) offer a command that does one thing or the other depending on the prefix argument. But what I like about the current choice is that it has late binding: you first press `g` and _later_ decide whether to just reexport or to tweak the input first. You get to see the updated results _before_ deciding whether you want to change the input, which I really like.

**Comment by oantolin** [comment] 2023-03-21 20:50
@mpereira. First the minor issue of the keybinding: Embark remaps `revert-buffer` to `embark-rerun-collect-or-export`, so whatever key bindings you used to use for `revert-buffer` should run `embark-rerun-collect-or-export`. Embark did not bind `g r` to `recompile`, it neither binds `recompile` to any key nor binds any command to `g r`; that must be something else in your configuration.

Now for the more substantial question about the behavior of `embark-rerun-collect-or-export`. You'd like a command that just reruns the search and updates the grep-mode results buffer. That's understandable but Embark won't be able to supply such a command. The suggested Embark workflow is that you run `embark-rerun-collect-or-export`, then optionally you can modify the minibuffer input to change the search being performed, and if you want a grep-mode buffer you simply export again.

There are several reasons for choosing this behavior:

1. It covers both the case of rerunning the same search and the case of tweaking the search terms slightly.

2. It allows Embark to stay generic: a command that reran the `grep` or `ripgrep` search directly would need to know what command line arguments were used, but that is an implementation detail of `consult-grep` and `consult-ripgrep` that Embark does not have access to (I mean, maybe it could with some hack, but the choice was made to not get mixed up in consult's business!).

3. You could still imagine a generic Embark rerun command, that reruns the command that created the candidates, _waits for it to finish producing new candidates_, then re-exports, but for an asynchronous command like `consult-grep` how is Embark supposed to know when the candidate list is complete? Indeed, it even makes sense for the list to never be complete! You could imagine an asynchronous command which continuously updates the candidate list until you `C-g`. What Embark does instead is let you decide when you have a candidate list that you want to export.

**Comment by oantolin** [comment] 2023-03-21 20:51
Thanks for quoting that @dschrempf, I think I still agree with that old comment.

**Comment by mpereira** [comment] 2023-03-22 17:25
@oantolin thanks for the additional context that I missed in the rest of the discussion in this issue. Your rationale makes sense. I'll probably eventually try to implement a function that performs the behavior you describe in your third point, and I'll share it here in case I do.

And thanks for your contributions to the Emacs ecosystem of packages. They make my life easier :)

**Comment by oantolin** [comment] 2023-03-22 17:51
@mpereira: I'd recommend giving the supported way a shot to see if it suits you. To recap, the support way is to use `embark-rerun-collect-or-export`, and then run `embark-export` again when the results are ready.

If you can't settle for a semi-automatic way to rerun the search and want a fully automatic way you can try the built-in `grep` family of commands or a package like [rg](https://github.com/dajva/rg.el) or [deadgrep](https://github.com/Wilfred/deadgrep), but of course, those would be used to do the initial search as well. If you want to keep using `consult-(rip)grep` and have a fully automated way to rerun the search, I see two ways to approach implementing this:

- Finish automating what Embark already does: you already have `embark-rerun-collect-or-export`, you'd just need to write code that figures out when `consult-(rip)grep` is finished and then run `embark-export` from the minibuffer again. To figure out when the search is finished you could monitor the `" *consult-async*"` buffer (note the buffer's name has a leading space).

This approach has the disadvantage that the minibuffer pops up and you see it being populated. If you use `(setq enable-recursive-minibuffers t)` that's not actually a problem per se, you can still use Emacs normally. And you could consider the minibuffer as a very detailed "progress bar" of sorts, so maybe it's not actually a disadvantage :P.

This suggests a second, harder approach:

- Save and rerun the search manually. You could store the search terms used with `consult-(rip)grep` and then rerun and refilter the search yourself. You could, for example, replace the function `embark--rerun-function` with a function of your own that stores the minibuffer input (your search terms) in some dynamic variable (that function does store the minibuffer input but in a _lexical_ variable where you can't get at it easily). Then you can parse the minibuffer input like `consult-ripgrep` does into command line arguments and an Emacs completions filter part, run the search using the command lines arguments, and filter the results with `completion-all-completions` or something like that. To rerun the search you may be able to leverage internal `consult` functions.

**Comment by uqix** [comment] 2024-04-27 10:28
Some cases not so convenient:

* `C-u consult-grep`, prompt path, prompt keywords, export, `g`, result: grep in **current project**, not the previous path
* `my/consult-grep/dir`, prompt path, prompt keywords, export, `g`, result: prompt path prefilled with previous keywords, then prompt keywords

``` emacs-lisp
(defun my/consult-grep/dir ()
  (interactive)
  (consult-grep '(4) nil))
```
