### ISSUE TITLE
embark-consult-goto-grep is broken in embark-collect buffers

### ISSUE THREAD

**Issue by minad** [oantolin/embark#612] opened 2023-03-12 12:16 UTC
The logic to override the `default-directory` seems broken. Sometimes it works depending on the windows I have open. I don't fully understand why we override the `default-directory` with the one from the `previous-window`. Is this only reasonable for the minibuffer? It seems that the assumption is that the action is run in the "original window" and as such `previous-window` makes sense. But in the case of collect buffers we may not have an original window?

**Comment by oantolin** [comment] 2023-03-12 13:28
> But in the case of collect buffers we may not have an original window?

In that case the "original window" is the collect buffer's window. This should work since collect buffers are setup with the correct default-directory upon creation. In this case, ``(previous-window)` is meant to be the collect window.

It would really help to figure out the best fix if you had a reproducible example.

**Comment by minad** [comment] 2023-03-12 13:30
I am not fond of adding additional properties to the candidates since this makes the "protocol" between the packages more complex. I argue that functionality depending on the default-directory must just work. It is worth to figure out the correct approach for this.

**Comment by minad** [comment] 2023-03-12 13:31
> It would really help to figure out the best fix if you had a reproducible example.

I think you need multiple windows with different default directories. Does this help?

**Comment by oantolin** [comment] 2023-03-12 13:50
OK, I've managed to reproduce this by deleting the window from which I ran `consult-grep` originally. I need a more reliable way to get the window the action is run from that `(previous-window)`.

**Comment by oantolin** [comment] 2023-03-12 13:52
I should have added that if Embark cannot find the target-window it just runs in the current window, making the current window the one you want for default-directory and previous -window irrelevant.

**Comment by oantolin** [comment] 2023-03-12 13:53
Let me just comment that default-directory propagation and guessing has caused me so many problems with Embark. Life would be so simple if all paths were absolute. 😄

**Comment by minad** [comment] 2023-03-12 14:00
> Let me just comment that default-directory propagation and guessing has caused me so many problems with Embark. Life would be so simple if all paths were absolute. 

Yes, I know. I hope we can finally get this right. I wonder if we can find a simple and general solution. It just boils down to getting the candidates and the appropriate environment (or subset of the environment, e.g., default directory).

**Comment by minad** [comment] 2023-03-12 14:45
I would prefer if we could stop relying on the window switching logic as much as possible and instead explicitly bind environments. We will still need the window switching anyway in order to ensure that actions are executed in the correct window, but the operation should still work even if the window is gone.

**Comment by oantolin** [comment] 2023-03-12 14:48
The embark action hooks all run too late: after the target window has been selected. I think maybe the best solution is to add a keyword parameter to hooks containing the originating window or the default-directory of the originating window. That way one can write a general around hook to let-bind the default directory in the target window to its value from the originating window.

**Comment by oantolin** [comment] 2023-03-12 14:48
Adding keyword parameters to hooks should be fine, since we've always said hooks should accept all keyword arguments.

**Comment by minad** [comment] 2023-03-12 14:58
> That way one can write a general around hook to let-bind the default directory in the target window to its value from the originating window.

Do you suggest that we introduce some "general" around hook which is always executed? Why not bake the functionality into the action invocation code directly then?

**Comment by oantolin** [comment] 2023-03-12 15:05
No, not for all actions. Most actions want the default-directory of the target buffer, which is what they currently get. This `embark-consult-goto-grep` is weird in that it wants the default directory of the buffer you called it from instead. That default-directory is conceptually part of the candidates, which are files, but it happens to not be stored inside the candidates.

My suggestion was to (1) provide a keyword parameter to hooks that gives access to either the window the action was called from or at least the default-directory of that window, (2) write an around hook that use that parameter to run an action with `default-directory` set to what it was in the window the action was called from, (3) add that around-hook to the default configuration for `embark-consult-goto-grep`.

**Comment by oantolin** [comment] 2023-03-12 15:08
I see this problem as a mismatch between conceptual understanding and implementation. I think of grep results as locations within files, but they aren't! They are implemented as an approximation to that: line and character position information and a _relative path_ to a file, relative to _some directory_ that's is not mentioned in the grep results and that needs to be kept tracked of separately.

**Comment by oantolin** [comment] 2023-03-12 15:14
Although maybe it is harmless to _always_ set `default-directory` to its value in the buffer you called the action from?

- If you are acting in a non-minibuffer, non-collect buffer, then the target buffer is the same as the current buffer, so the `default-directory` wouldn't change.
- If you are acting in the minibuffer, the `default-directory` is usually the one from the buffer you were in when you ran the command that opened the minibuffer from. So often we'd just be setting it to what it was.
- If you are acting in a collect buffer maybe you actually always want the collect buffer's `default-directory` since that was the one inherited from the context in which the candidate list was created.

This would be a big change. I'd suggest making the change in a new branch and you and I testing in normal usage for a week to see if it doesn't break tones of other actions.

**Comment by minad** [comment] 2023-03-12 15:30
> Most actions want the default-directory of the target buffer, which is what they currently get.

I am confused what you mean by target buffer.

> I see this problem as a mismatch between conceptual understanding and implementation.

Yes, indeed. We should first get to the ground of that. As far as I have understood the data we are acting on are not only the candidate strings but also the dynamically bound environment and the local environment from the window/buffer, where the minibuffer command was initiated. The grep candidates are only meaningful if the environment (default-directory) is also present. Other candidate types may need additional dynamic variables.

> Although maybe it is harmless to always set default-directory to its value in the buffer you called the action from?

Yes, this is what I had in mind, and maybe even more general where we could ensure that more dynamic variables are handled similarly if they are needed such that the candidates are meaningful.

**Comment by oantolin** [comment] 2023-03-12 16:37
> I am confused what you mean by target buffer.

This is the buffer in which the action should run. It is slightly complicated to determine:

- For actions in "normal" buffers (normal means "not one of the cases listed below", it is the current buffer.
- For actions in the minibuffer it is the buffer that was current before running the command that led to the minibuffer.
- For actions on a completion candidate in a `*Completions*` buffer or in an Embark Collect buffer, it is the buffer that was before running the command that generated the candidates _initially_. That "initially" means that if you are in a buffer A, run some completion commands, collect the candidates into a buffer, then collect some of those candidates in B into a third collect buffer C, when you runs actions on candidates in C they still need to run in buffer A.

**Comment by oantolin** [comment] 2023-03-12 16:43
Things are complicated for `default-directory`, since you don't always want the `default-directory` in either the target buffer or in the buffer you are running the action from. For example, if you are in buffer A, run `find-file`, navigate to a directory D, and then run some action on a `find-file` candidate you want `deault-directory=D`, but the value of `default-directory` in the minibuffer is not D, but is the same as `default-directory` in the buffer A.

Embark has some heuristics to guess the `default-directory` you actually want, which, judging by the low frequency of complaints, actually work fairly well.

**Comment by oantolin** [comment] 2023-03-12 16:43
This is just one case were my heuristics broke down. I'll fix it, just need to think about it a bit.

**Comment by minad** [comment] 2023-03-12 18:13
> Things are complicated for default-directory, since you don't always want the default-directory in either the target buffer or in the buffer you are running the action from. For example, if you are in buffer A, run find-file, navigate to a directory D, and then run some action on a find-file candidate you want deault-directory=D, but the value of default-directory in the minibuffer is not D, rather it is the same as default-directory in the buffer A.

I don't fully understand this example. Do we not use the "full candidate" including the base string for injection? Then you can still use default directory A.

But in the case of collected candidates this won't work since the base string is lost. If we want to be correct we also have to store the base string.

**Comment by oantolin** [comment] 2023-03-12 19:57
Sorry, you're right, we do now use the "full candidate" for injection. Embark still needs the `default-directory` guessing and propagating for `*Completions*` buffers.

The `default-directory` needs special treatment because in `*Completions*` buffers you can find candidates that are meant to be relative paths but are not relative to the `default-directory` in the `*Completions*` buffer. (Embark actually installs advice that corrects the value of `default-directory` in `*Completions*` buffers, and it makes everything better as far as I can tell; I have received zero comments either positive or negative about this advice, so I think nobody relies on the value of `default-directory` in `*Completions*` buffers.)

Another advantage of treating `default-directory` specially, namely of setting the correct value in Embark Collect and in `*Completions*` buffers, is that it enables the direct use of commands such as `ffap` or `shell`, etc., without having to run them through `embark-act`.

And more generally, any dynamic variable that needs to be remembered for the candidates to be meaningful would need special treatment (at least being saved and restored when it's time to run an action; though maybe that's not what you call special), of course, it's just that `default-directory` is the only one I am aware of.

**Comment by minad** [comment] 2023-03-12 20:04
> Another advantage of treating default-directory specially, namely of setting the correct value in Embark Collect and in *Completions* buffers, is that it enables the direct use of commands such as ffap or shell, etc., without having to run them through embark-act.

I see. This makes sense. Also just when typing C-x C-f you will end up in the right directory. I agree we should keep this special treatment.

> And more generally, any dynamic variable that needs to be remembered for the candidates to be meaningful would need special treatment (at least being saved and restored when it's time to run an action; though maybe that's not what you call special), of course, it's just that default-directory is the only one I am aware of.

Yes, sure. This is what I mentioned before. A candidate string is only meaningful together with its base string and its dynamic environment, which needs to be remembered (at least partially). 

But I am distinguishing between special treatment and just remembering. We may have to remember more variables if the need comes up, if some completion commands depend on certain variables being present. However for the other variables we probably don't need similar complex special guessing like the one of default-directory which is either taken from some buffer or derived from the base string.

**Comment by oantolin** [comment] 2023-03-13 19:50
I think it is safe to just always use the `default-directory` from the buffer you run `embark-act` in. I made that change in a branch, please test it for a while. I'll test it too, and if change the `default-directory` likes this really doesn't screw a bunch of other actions up, I'll merge. 0c6903cb0b51437a88bb32a82ab0c5ad6d626b85

**Comment by oantolin** [comment] 2023-03-14 18:03
I'm fairly convinced this can be merged. Not because I'm 100% certain this new `default-directory` value is always better, but because I'm like 96% sure it is better and I think I need to crowd-source finding any weird edge case. 😛

**Closed** 2023-03-14 18:25 UTC
