### ISSUE TITLE
How to avoid file dialog?

### ISSUE THREAD

**Issue by okamsn** [oantolin/embark#39] opened 2020-09-19 18:02 UTC
How can I make the commands run via Embark not use the file dialogs?

The variable `use-file-dialog` can be set to nil, but that also affects commands that use the mouse, such as the menu bar and tool bar. Is there a way to set this variable only for commands run via Embark?

Thank you.

**Comment by oantolin** [comment] 2020-11-11 21:48
Hi! I'm sorry I was away from GitHub so long. I'm not sure I understand your issue. I have the variable `use-file-dialog` set to `t` (which I believe is the default), but I never see file dialogs when using embark. (In fact, since I don't use the menus or mouse, I don't see file dialogs at all!)

Can you give me an example of when the file dialog popups undesired?

**Comment by okamsn** [comment] 2020-11-12 23:01
On Linux, in Selectrum, if I try to delete a file using the `d` key from within `find-file`, a file selector is opened that asks me to move a file to the trash (I have set `delete-by-moving-to-trash` to `t`). 

This makes me need to select a file for deletion twice.

**Comment by jakanakaevangeli** [comment] 2020-12-04 20:03
I can also reproduce this issue with `emacs -q` (on emacs 27.1, Xorg):
```
(load "~/path/to/embark.el")
(define-key minibuffer-local-map (kbd "M-o") 'embark-act)
```
and then when I press `C-x C-f M-o o`, a file dialog shows up.

**Comment by oantolin** [comment] 2020-12-04 21:07
Oh! That does indeed reproduce the error, thanks! I'll go about fixing it now. (I'm sorry @okamsn, I had tried to reproduce it with `embark-act-noexit` and never tried `embark-act`.)

**Comment by oantolin** [comment] 2020-12-04 21:21
OK, I think I fixed this. e6f70ca3f1bfd264c17feb2e1e5ad8fbd9a67660

Please test.

**Comment by jakanakaevangeli** [comment] 2020-12-05 09:40
Thank you, it works fine for me now.

**Comment by oantolin** [comment] 2020-12-05 15:55
I'll close this issue then. Please reopen if I missed some edge case or something.

**Closed by oantolin** 2020-12-05 15:55 UTC
