### ISSUE TITLE
updating bookmark locations

### ISSUE THREAD

**Issue by jdtsmith** [oantolin/embark#352] opened 2021-08-21 13:53 UTC
With the new `set` action on bookmarks, if you have enabled preview from consult-bookmark, bookmark locations cannot be updated.

1. Navigate or narrow to a bookmark.
2. Position is automatically previewed.
2. embark-act, `s` to set the bookmark to a new position.
3. The same position is re-recorded.

It would be great if "set" used the original (pre-preview) location to update an existing bookmark's position.

**Comment by oantolin** [comment] 2021-08-21 17:00
As a work around, you can run the `set` action as a quitting action. This first quits the minibuffer which also cancels the preview, returning to the correct location before setting the bookmark.

Consult preview does unfortunately interfere with several actions when run as non-quitting. @minad has suggested working around this Consult preview quirk in Embark by making all actions quit, and then restarting the command for the non-quitting ones, but maybe now we could handle this for specific actions by a clever use of pre-action and post-action hooks to stop and resume preview?

**Comment by oantolin** [comment] 2021-08-21 18:32
> but maybe now we could handle this for specific actions by a clever use of pre-action and post-action hooks to stop and resume preview?

Probably not.

**Comment by jdtsmith** [comment] 2021-08-21 18:57
Aha, that's the difference.  I thought this had worked before.  But you had talked me into default quitting (which I'm enjoying quit a bit).  What's the current status of altering the defaults for specific actions like bookmark set?  I didn't fully parse the long discussion we had about that. Thanks.

**Comment by oantolin** [comment] 2021-08-23 14:49
> But you had talked me into default quitting

You mean we talked you into _not_ quitting after actions by default, right?

> What's the current status of altering the defaults for specific actions like bookmark set?

It hasn't been implemented. I'm not sure it's really necessary. For this specific issue, I personally just use `C-0 C-;` or `C-- C-;` (`embark-act` just needs any prefix argument and the `0` and `-` keys are close to `;`). Is passing the prefix argument too awkward?

**Comment by jdtsmith** [comment] 2021-08-23 15:28
> > But you had talked me into default quitting
> 
> You mean we talked you into _not_ quitting after actions by default, right?

Right.  Not quitting.  Which is normally the right thing IMO. 

> > What's the current status of altering the defaults for specific actions like bookmark set?
> 
> It hasn't been implemented. I'm not sure it's really necessary. For this specific issue, I personally just use `C-0 C-;` or `C-- C-;` (`embark-act` just needs any prefix argument and the `0` and `-` keys are close to `;`). Is passing the prefix argument too awkward?

Not too awkward, if you remember.  But if you always have to remember to add a prefix before some actions, that seems like a poor default!  Since bookmark set is "broken" with non-quitting (and not just from out of date info), basically you'll never want it to continue!  

Maybe there's some solution closer to consult preview, which is the true source of the issue?  Perhaps consult could just remember the active buffer at its invocation, and let embark-act (when called from the minibuffer) know somehow (without any undue coupling).  Then embark-act could restore that temporarily before action.

**Comment by oantolin** [comment] 2021-08-23 15:46
Well, the bookmark set action isn't broken if you use it from the built-in Emacs bookmark commands, only from `consult-buffer` with preview activated. It would be nice if there were an easy way to pause and resume the preview. The exposed `consult--preview-function` could, for example, take an optional argument.

**Comment by minad** [comment] 2022-04-07 23:53
@oantolin The refined preview protocol I introduced in https://github.com/minad/consult/pull/546 makes sure that the state function is always called with the `preview` action and candidate `nil` just before exiting new minibuffer. So it would make a lot of sense to do the same in Embark.

1. (funcall preview-function 'preview nil)
2. run the embark action
3. (funcall preview-function 'preview last-previewed-candidate)

**Comment by oantolin** [comment] 2022-04-07 23:56
With the new consult preview protocol we can pause and resume preview in pre and post action hooks, so the next question is should we? 

I think it's reasonable to say that embak actions should behave the same whether or not there is a preview, and that would be achieved by pausing and resuming. The only downsides I can think of now are: (1) maybe some people depend space-bar-heating-style on actions affecting the preview buffer (but those people can just remove the pre and post action hooks if they want), and (2) maybe the screen will flicker a bit.

I don't think we need to worry about (1) since users can remove the hooks. And if (2) is too much of a problem, instead of doing this for all consult commands we can curate a list of those for which it is deem essential.

**Comment by oantolin** [comment] 2022-04-07 23:56
Ha! As usually @minad was faster to comment than I was.

**Comment by minad** [comment] 2022-04-07 23:59
So you want to have some functions `consult--pause-preview` and `consult--resume-preview` which you could put into the `pre-command-hook` and `post-command-hook` respectively?

**Comment by oantolin** [comment] 2022-04-08 00:00
I was thinking of writing those myself in embark-consult. I mean, it's just calling the preview function with nil and the target.

**Comment by oantolin** [comment] 2022-04-08 00:01
And I'd put them in embark-pre/post-action-hooks with key :always

**Comment by oantolin** [comment] 2022-04-08 00:03
Oh, in case of manual preview the last previewed target may not be the embark target! I hadn't noticed that complication. I don't think the consult API let's me figure out what to preview, does it?

**Comment by oantolin** [comment] 2022-04-08 00:07
Could maybe `(funcall preview-function 'preview nil)` return the candidate it was previewing?

**Comment by minad** [comment] 2022-04-08 00:07
Hmm the problem is that I don't expose the low level interface currently, only `consult--preview-function` which encapsulates all the logic which checks if preview should indeed happen, debouncing and so on. I am not sure I want to expose the low level interface in addition to the high level interface since then the internal state inside of the `consult--preview-function` closure will get messed up. Therefore we probably have to use a high level interface. Something like this:

~~~ elisp
(funcall consult--preview-function 'trigger)
(funcall consult--preview-function 'pause)
(funcall consult--preview-function 'resume)
~~~

**Comment by oantolin** [comment] 2022-04-08 00:11
I'm a little confused, isn't the only problem with your plan:

1. (funcall preview-function 'preview nil)
2. run the embark action
3. (funcall preview-function 'preview last-previewed-candidate)

that I have no way of knowing what last-previewed-candidate is?

And if that is correct, it can be solved by having (funcall preview-function 'preview nil) return the last-previewed-candidate.

**Comment by oantolin** [comment] 2022-04-08 00:11
What am I missing?

**Comment by oantolin** [comment] 2022-04-08 00:13
Ah, are you saying that the `preview-function` from your 3 step plan is *not* the value of `consult--preview-function`?

**Comment by minad** [comment] 2022-04-08 00:19
> Ah, are you saying that the preview-function from your 3 step plan is not the value of consult--preview-function?

No, my 3 step plan is what would happen internally, behind the scenes. But this is not what we can expose to Embark I think.

**Comment by oantolin** [comment] 2022-04-08 00:21
So what does  the exposed consult--preview-function function do then?

**Comment by minad** [comment] 2022-04-08 00:23
> So what does the exposed consult--preview-function function do then?

It does everything. It is a big mess. See https://github.com/minad/consult/blob/b50118f6e9ddf296c48e052d8b8d6dc6fa419e6f/consult.el#L1378-L1406. It checks the events and timers, retrieves the candidate and then calls the :state function with the candidate if all criteria are satisfied.

**Comment by oantolin** [comment] 2022-04-08 00:31
I see. I'd love for it have a trigger/pause/resume argument as you mentioned above.

**Comment by minad** [comment] 2022-04-08 00:39
Okay. But I have to refactor this function a bit before adding this. Otherwise it will just get out of hand.

**Comment by oantolin** [comment] 2022-04-08 00:56
Maybe there is another way. Currently embark decides what the target buffer is when you  all embark-act, but it could do that earlier, at the time it records the command that opened the minibuffer. If I did that consult could stay as is.

**Comment by minad** [comment] 2022-04-08 00:57
I see. This seems like a much simpler solution.

**Comment by minad** [comment] 2022-04-08 00:58
The only downside is that it would apply to all actions in all cases then. Are there space bar heating workflows where one wants to determine the target buffer late?

**Comment by oantolin** [comment] 2022-04-08 01:52
Not that I know of, I think the more desirable behavior is to use the buffer that opened the minibuffer, but if someone does complain it would not be hard to make this configurable. Possibly the late binding strategy could even be carried out by something like overriding embark--target-buffer in a pre-action (I'd have to think about that). And if not, and someone really really wants late binding it would be easy to add a user option.

I'll implement the early caching of the target buffer tonight or tomorrow and test to see exactly how preview interacts with it. Since embark displays the target buffer in some window if none display it, there might be some funny interaction.

**Comment by oantolin** [comment] 2022-04-08 02:17
Oh, no. I just realized Embark storing the target buffer early isn't enough! Consider the case of `consult-line`. I sometimes use it with `embark-insert` to duplicate a far away line from the current buffer: put point were you want the copy to appear, use `consult-line` to find the line you want, run `embark-insert` as a quitting action.

In that workflow it's essential to use `embark-insert` as a quitting action, because otherwise you wind up duplicating the line right above its location, instead of at the original place you put point. This is because Consult preview has more side-effects than switching buffers, it also moves point!

The early binding strategy (of having `embark--target-buffer` be the buffer that was current when you ran `consult-line`) doesn't fix this case.

What *would* fix all cases is the pause/resume preview strategy we discussed. Another way to do this is an old suggestion of yours, @minad: to run non-quitting actions as "quit, act, restart". If we did it that last way, I think we'd need to put more effort into restoring state when restarting. Currently `embark--restart` only restores the minibuffer contents. In non-default completion UIs there is also the currently selected candidate that should probably be restored as well. And for consult users that trigger preview manually, maybe also the preview state should be restored (probably this last thing is not a big deal).

**Comment by oantolin** [comment] 2022-04-08 02:27
You might say that the example above does not completely kill the early binding approach, maybe I just need to store the target buffer *and* the location of point in it. But I'd argue that for point location late binding is the natural approach. Indeed, sometimes when I'm doing the `consult-line`+`embark-insert` trick, I noticed I really wanted the copy one line below, say, so without closing the minibuffer I switch over to the buffer, move a line down, and switch back to the minibuffer to carry out the procedure. It feels very natural that `embark-act` "sees" the updated point location. But `embark-act` can't tell whether *I* moved point or Consult preview did.

**Comment by minad** [comment] 2022-04-08 02:28
> this is what I do instead of cape-line

You told me about your workflow before. I was just about to suggest that you should simply reinstall cape. :laughing: 

> The early binding strategy (of having embark--target-buffer be the buffer that was current when you ran consult-line) doesn't fix this case.

I am confused. I thought we are talking about non-quitting actions, so why does `embark-insert` as a quitting action create issues here?

> Another way to do this is an old suggestion of yours, @minad: to run non-quitting actions as "quit, act, restart". 

This wasn't a good idea. It is much more difficult to restore all the state. Furthermore the candidate list has to be regenerated which makes this a no-go for async Consult commands. The way Embark does it currently is more conservative, preserve as much as possible and only destroy state if needed via embark--restart.

**Comment by oantolin** [comment] 2022-04-08 02:36
> I am confused. I thought we are talking about non-quitting actions, so why does `embark-insert` as a quitting action create issues here?

I'm sorry, I worded that confusingly! The consult-line+embark-insert thing works right now if you run `embark-insert` as a quitting action, and after describing the procedure I went on to discuss what it would take to make it also work as a non-quitting action with preview on. Notice that with embark-insert as a quitting action the behavior is the same whether or not preview is on, but with a non-quitting action preview affects the semantics: with preview off you get cape-line, with preview on you duplicate the line right above itself.

**Comment by minad** [comment] 2022-04-08 02:46
Okay, understood. I agree that ideally the semantics should not be affected by preview. But then I am not sure what to make out of what you said here:

> But embark-act can't tell whether I moved point or Consult preview did.

So it seems that sometimes you actually want preview to modify the semantics? I mean preview obviously is more than preview as soon as you start recursive editing which is why I jumped through these hoops to fully initialize previewed buffers.

I must admit I've kind of given up on such actions like embark-insert/bookmark-set in the presence of preview since I get totally confused by that. It seems to me as if we want a bit too much here and combine two things which just don't go so well together. 

If both preview and non-preview are needed for non-quitting actions, one possibility could be to allow the user to pause/resume previewing manually. But the code required to implement this would just be the same as for Embark preview pause/resume (https://github.com/oantolin/embark/issues/352#issuecomment-1092321646).

**Comment by minad** [comment] 2022-04-08 02:52
Hmm. Is the problem the distinction between these two scenarios?

- Recursive editing (and then switch buffers, do whatever) without Consult preview. Then Embark should pick up the changed target buffer (late binding).
- Consult preview. Then Embark should not pick up the changed target buffer (early binding).

But what if you want still want the Consult preview to be picked up - as if you did the buffer switch manually?

**Comment by oantolin** [comment] 2022-04-08 02:54
> I mean preview obviously is more than preview as soon as you start recursive editing

That is an excellent point I hadn't considered! If I start recursively editing a previewed buffer and go back to the minibuffer, where do I actually want embark actions to take place? I am not sure! I think since in this case I manually edited the preview buffer I would naturally expect the action to happen in the preview buffer wherever I left point! So that's a case where the current behavior feels more natural. Weird: if I just preview I want the preview ignored and if I preview and edit, I want the action to happen in the preview? I'm not really sure, but it seems that way, thinking about `embark-insert` at least.

> I must admit I've kind of given up on such actions like embark-insert/bookmark-set in the presence of preview since I get totally confused by that.

Just run the actions as quitting. They are not confusing then: it's as is the previews never happened.

Maybe the best answer is to leave things as they are! Then you have a choice: to take preview into account use a non-quitting action, if you want to ignore preview use a quitting action. That's fairly easy to remember, I think.

**Comment by oantolin** [comment] 2022-04-08 02:56
Ha! I've come full-circle, haven't I? The very thing I wrote in this issue was: "As a work around, you can run the set action as a quitting action." Well, I have evolved, maybe now I'm saying that's not a work around, that's just how you say "ignore the side-effects of preview, please".

**Comment by minad** [comment] 2022-04-08 02:59
> Maybe the best answer is to leave things as they are! Then you have a choice: to take preview into account use a non-quitting action, if you want to ignore preview use a quitting action. That's fairly easy to remember, I think.

> Ha! I've come full-circle, haven't I? The very thing I wrote in this issue was: "As a work around, you can run the set action as a quitting action." Well, I have evolved, maybe now I'm saying that's not a work around, that's just how you say "ignore the side-effects of preview, please".

Yes, maybe it is most natural to keep things like this since in the presence of recursive editing there is just not a good answer. By taking preview into account (non-quitting), Embark picks up what the user sees, which is natural. If you quit Embark picks up what you see after the window configuration restoration, which also makes sense.

Close this as wontfix then? Also in the name of simplicity of the consult--preview-function which is already messy enough. :-P

**Comment by oantolin** [comment] 2022-04-08 03:07
> Yes, maybe it is most natural to keep things like this since in the presence of recursive editing there is just not a good answer. By taking preview into account (non-quitting), Embark picks up what the user sees, which is natural. If you quit Embark picks up what you see after the window configuration restoration, which also makes sense.

Agreed! Closing as wontfix, and maybe I'll add a note about this in the Consult section of the README.

> Also if we can avoid adding further entangling of Embark/Consult that way, this is good, isn't it?

Yes.

>  Until now embark-consult doesn't look that bad, except maybe the recent export buffer reverting addition which I find a bit ugly.

It _is_ ugly, but ugly isn't the real problem. The real problem is that it is brittle and slower than necessary (i.e., it can waste close to 0.6 seconds, I believe, if you are unlucky with the timing). A `consult--async-done-hook` or something like that would be nice.

**Closed by oantolin** 2022-04-08 03:07 UTC

**Comment by minad** [comment] 2022-04-08 03:14
> It is ugly, but ugly isn't the real problem. The real problem is that it is brittle and slower than necessary (i.e., it can waste close to 0.6 seconds, I believe, if you are unlucky with the timing). A consult--async-done-hook or something like that would be nice.

Okay. Let's address this at some point. I hope there is not too much fall out from my `:state` API change.

**Comment by oantolin** [comment] 2022-04-08 03:18
Yeah, the hacky revert does work for now and is better than not having it at all. We can improve it later.
