### ISSUE TITLE
improvement ideas 

### ISSUE THREAD

**Issue by a13** [oantolin/embark#5] opened 2020-05-16 19:49 UTC
- make predicate- and regexp-based classifiers (or a generator for these)

- reuse thingatpt.el machinery somehow (can't verbalise the exact idea yet)

to be continued …

**Comment by a13** [comment] 2020-05-16 20:15
* check if `(embark-target)` is not nil (to avoid errors)

**Comment by oantolin** [comment] 2020-05-16 20:32
> * check if `(embark-target)` is not nil (to avoid errors)

Oh! That's not supposed to happen! Do you have a recipe to reproduce a situation where `(embark-target)` is nil when it shouldn't be?

**Comment by oantolin** [comment] 2020-05-17 16:48
> > check if (embark-target) is not nil (to avoid errors)

>  Do you have a recipe to reproduce a situation where (embark-target) is nil when it shouldn't be?

Found a recipe: write a command that uses `(embark-target)` and then uses `call-interactively` to transfer control to some other command. I added the non-nil check before injecting now.

**Comment by oantolin** [comment] 2020-05-17 17:51
An improvement idea which I've just implemented is to be able mark certain commands as not requiring confirmation: `(put 'kill-buffer 'embark-ratify t)`.

**Comment by karthink** [comment] 2020-05-19 02:40
The shell command actions (`!`, `&`, `|`) require typing at the beginning of the prompt, whereas `embark-act` positions the cursor at the end after the selection in the minibuffer. This might be true of other embark actions that I haven't tested yet. Can you modify them so they DWIM?

**Comment by karthink** [comment] 2020-05-19 03:33
This is tangential and probably a significant effort but it may help to think about this for the future:

Make `embark--compute-target` handle multiple candidates.

This is not useful at the minibuffer itself since the minibuffer only has one selection at a time (by default). It can really shine in a completions buffer along with a way to mark multiple candidates. For files and buffers this just turns a completions buffer into dired-lite and ibuffer-mini, but for general symbols this can be arbitrarily powerful.

`ivy` has `ivy-mark` that does this, but it's not well integrated at the moment since ivy functions have to be written with a special `:multi-action` section in calls to `ivy-read` and very few are.

I'm trying to write the glue to add the ability to mark files in completions buffers, but `choose-completion` isn't the easiest code to follow.

**Comment by oantolin** [comment] 2020-05-19 04:30
> The shell command actions (`!`, `&`) require typing at the beginning of the prompt

I have a plan. I'll change the `embark-ratify` property to a more general `disembark` property that's a hook, so we can add things like an auto-confirm function (which would be the new `embark-ratify`) or a move-to-beginning-of-line function for `|` and `&`.

> Make embark--compute-target handle multiple candidates.

That's the dream right there. Even deciding on what it means would take some effort. But yes, that would be great. I guess we could have:

- automatic multiplication: run commands that have no idea about multiple candidates by simply looping over the candidates
- natively multiple commands: some commands could take a list of candidates as an argument
- for the minibuffer we could have: act on just the top candidate (like now), or on all candidates
- for the completions buffer: mark some candidates --there could a "mark candidate at point", "mark all matching regexp", "toggle mark/unmarked"

That's ... a lot of work. And not just easy work (implementation), hard work too (designing the features).

>  choose-completion isn't the easiest code to follow.

Amen to that.

While we are dreaming, another dream is to be able to `choose-completion` even after the minibuffer is dead. This would effectively turn the completions buffer into `ivy-occur`!

**Comment by oantolin** [comment] 2020-05-19 06:06
> The shell command actions (`!`, `&`) require typing at the beginning of the prompt

Done, it should put point at the beginning out the box now. See the updated README for instructions on how to do similar post-processing after injecting the target for other commands.

**Comment by karthink** [comment] 2020-05-22 04:19
If I understand correctly, this function handles shell quoting?

```
(defun embark--shell-prep ()
  "Prepare target for use as argument for a shell command.
This quotes the spaces, inserts an extra space at the beginning
and leaves the point to the left of it."
  (let ((contents (minibuffer-contents)))
    (delete-minibuffer-contents)
    (insert " " (replace-regexp-in-string "\\s-" "\\\\\\&" contents))
    (beginning-of-line)))
```

The `replace-regexp` is not a shell-agnostic way of doing this. Consider 

```
(insert " " (shell-quote-argument contents))
```
instead?

**Comment by oantolin** [comment] 2020-05-22 04:44
> shell-quote-argument

Will do, thanks!

**Comment by oantolin** [comment] 2020-05-23 17:43
> (insert " " (shell-quote-argument contents))

Huh, that actually quotes too much! It's meant to pass the argument literally to a shell command. For example, it quotes `~`, which you'd actually want unquoted so the shell has a chance to replace with the home directory.

**Comment by karthink** [comment] 2020-05-23 19:23
My bad, I thnk the right function is `shell-quote-wildcard-patttern`:
```
Quote characters special to the shell in PATTERN, leave wildcards alone.
```

`(shell-quote-wildcard-pattern "~/some directory/file with spaces.txt")`

**Comment by oantolin** [comment] 2020-05-23 19:28
Yes, that works, thank you!

**Comment by karthink** [comment] 2020-05-24 22:55
New action: `embark-find-file-external` to open files using OS defaults?

The following works but only on Linux. 
```
(defun embark-open-extern ()
  "Open externally"
  (interactive)
  (call-process-shell-command
   (format "%s %s"
           (cond
            ((eq system-type 'nt) "someprogram"
             (eq system-type 'darwin) "someprogram"
	     (t "xdg-open")))                                   
	   (shell-quote-wildcard-pattern (embark-target)))
                              nil 0))
```

**Comment by oantolin** [comment] 2020-05-25 21:37
> New action: `embark-find-file-external` to open files using OS defaults?

Good idea, I've added a version (bound to `x`, as you suggested) in commit 9769863.

I bet almost all Emacs user's have a command to open files externally lying around. This is mine:

```elisp
(defun embark-open-externally (file)
  "Open file using system's default application."
  (interactive "fOpen: ")
  (if (and (eq system-type 'windows-nt)
           (fboundp 'w32-shell-execute))
      (w32-shell-execute "open" (expand-file-name file))
    (call-process (pcase system-type
                    ('darwin "open")
                    ('cygwin "cygstart")
                    (_ "xdg-open"))
                  nil 0 nil
                  (expand-file-name file))))
```

I've used it on Linux and Windows (native). I'm wouldn't swear it works on Mac OS or on Cygwin, but those are the commands I've seen people mention. I think it might as well be a normal command, rather than operating just on `embark-target`, and I like avoiding the shell (and the concomitant quoting) if possible.

**Comment by oantolin** [comment] 2020-05-25 21:38
> Additionally I'm using `open-file-other-tab` and `open-file-other-frame`, but I'm not sure those are good candidates for inclusion.

Those seem slightly specialized, let's leave them for users to add if they want.

**Comment by oantolin** [comment] 2020-05-25 22:07
> * reuse thingatpt.el machinery somehow (can't verbalise the exact idea yet)

Well, one thing that can be done is to act on the file or symbol at point. I added that in commit 413fe52. It's kind of cool, actually. I've often wanted to lookup help or go to the definition of Emacs Lisp functions or variables in emails or markdown buffers and now it's easy.

I'm not sure these should be on by default, because that involves loading ffap and thingatpt.

**Comment by oantolin** [comment] 2020-06-04 16:28
I wanted to mention here, that a keymap of commands that act on the region has been added. It is offered when the region is active.

**Comment by oantolin** [comment] 2020-06-13 16:51
I think all of the improvements discussed here have been made. And since it feels like we got most of the low-hanging fruit by now, I think in the future I'd prefer one issue per improvement idea, so I'm closing this issue now.

**Closed by oantolin** 2020-06-13 16:51 UTC
