### ISSUE TITLE
Injected candidates from collection buffer don't work for programmed completion

### ISSUE THREAD

**Issue by alphapapa** [oantolin/embark#517] opened 2022-06-13 21:37 UTC
Apologies if there's an existing issue for this; a quick scan of the issues list didn't turn up anything.

I recently added a new command to org-ql, [org-ql-find](https://github.com/alphapapa/org-ql#org-ql-find), which uses default Emacs completion APIs.  It uses dynamic, aka "programmed" completion, because it's not doing simple substring completion.  

While it works very well with Vertico, it doesn't work with Embark.  For example, when I use `embark-collect-snapshot`, the snapshot buffer lists the candidates, but when I activate a candidate, it causes an error, because Embark injects the candidate string into the minibuffer, while `org-ql-find` uses a different string, the org-ql search query, to find the candidates.

I think a way to solve this would be for Embark to record the minibuffer input and inject it instead of the candidate.  But, of course, it would then need to select the candidate somehow, and I haven't figured out how to do that yet.

Thanks for your work on Embark!

**Comment by minad** [comment] 2022-06-13 21:48
Other dynamic commands like consult-grep have the same issue. Unfortunately the standard Embark behavior does not work for these commands. They need a special injection logic or a default action override.

**Comment by minad** [comment] 2022-06-13 21:50
See https://github.com/oantolin/embark/blob/63f0d4dc09afb058450dc10dd3916027a93ee487/embark-consult.el#L210-L211

**Comment by oantolin** [comment] 2022-06-14 02:27
I also think a default action override is the best way to handle this problem.

After a quick look at the `org-ql-find` I think the best bet would be to add the markers held in the hashtable called `table` to the individual completion candidates as text properties, and write a little function to use as the default function override that retrieves the marker from the text property, jumps to it, displays the buffer and runs `org-ql-find-goto-hook`.

**Comment by oantolin** [comment] 2023-02-27 02:32
I regard this as essentially unfixable in Embark, but at the same time the tools we have to mitigate the problem seem sufficient. Commands like `org-ql-find` are weird in that the completion candidate they show don't _complete_ the input at all: the fact that typing in a candidate does _not_ select that candidate is pretty weird when you think about it. The problem is that Embark has no way of knowing you are using the completion UI for a task that is not really completion. Embark's mechanisms are made for the common case in which typing in a candidate at a minibuffer prompt, you know, selects said candidate!

What we have available for these (important but) non-standard completion sessions is the notion of a "default action override". The normal default action is precisely to rerun the command and type the candidate back in, and here what you want is precisely to do something different. So you'd need to write a function that given an `org-ql-find` completion candidate does what ever `org-ql-find` does when you select that candidate (which I believe is jumping to that heading, right?). Now, if the candidate string itself does not contain enough information to figure out what do, my suggestion is to simply add that information to the candidate string in text properties. This has worked well for all the consult search commands, and I don't see any reason to think the model breaks down here.

So I am going to close this issue in the belief that current Embark mechanisms are enough to handle this, but I welcome any further discussion or reopening if you think it is warranted.

**Closed by oantolin** 2023-02-27 02:32 UTC
