### ISSUE TITLE
async symlink from embark collect buffer error

### ISSUE THREAD

**Issue by dinojr** [oantolin/embark#598] opened 2023-02-11 09:30 UTC
Symlinking with dired-do-symlink, with async-dired-mode set to true gives the following error message, after the symlinking succeded:

```
 (wrong-type-argument stringp nil)
  dired-uncache(nil)
```
There is no error with async-dired-mode set to nil

**Comment by oantolin** [comment] 2023-02-11 22:21
As far as I can tell I do not have any "async-dired-mode" in my Emacs. Is it from some external package?

**Comment by oantolin** [comment] 2023-02-11 22:22
There also doesn't seem to be any package with both "async" and "dired" in the name available on GNU ELPA or MELPA.

**Comment by minad** [comment] 2023-02-11 22:53
@oantolin Afaik it is part of the Async package. I don't use it, but it wouldn't astonish me if if the Dired modifications don't work with Embark. Maybe it is an issue which should rather be fixed in Async then?

**Comment by oantolin** [comment] 2023-02-11 22:58
> EDIT: I think @dinojr meant `dired-async-mode`.

I don't have that either, Orderless would have found it too. 😉 

It makes sense that it would be in the async package, I wouldn't have found that since I was looking for both "async" and "dired" in the name.

It might be a little soon to decide whether this problem is Embark's fault or Async's, if setting it up isn't too complicated I might take a look.

**Comment by oantolin** [comment] 2023-02-11 23:04
I'm not completely certain, but It looks like 213ced2c5d30848ec03bb8599590b111b27c7839 is the culprit. Maybe there is a better way to keep dired from reusing the exported buffers.

By the way, I think the issue is with export, not collect, since the dired commands wouldn't make much sense in a collect buffer.

**Closed** 2023-02-11 23:25 UTC

**Comment by oantolin** [comment] 2023-02-11 23:27
Yep, I think that commit was the problem. And it turns out dired provides a function called `dired-unadvertise` that can be used to better fix the problem addressed by PR #527.
